(()=>{const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];

const cameraInfo={grip:['FRONT • HANDLING','Camera grip','Hold the grip with your right hand and support the lens from underneath with your left hand.','Use this two-hand hold whenever you shoot handheld.'],lens:['LENS • 18–55MM','Zoom lens','The zoom ring changes framing from wide 18mm to tighter 55mm.','18mm for wide scenes, 35mm for everyday use, 50–55mm for portraits and product detail.'],afmf:['LENS SWITCH','AF / MF switch','AF means autofocus. MF means manual focus. Keep it on AF while learning.','Use MF only when autofocus struggles or you deliberately want manual focus.'],flash:['TOP • FLASH','Built-in flash','The pop-up flash gives direct frontal light. It can help in a pinch but often looks harsher than window light.','Use it when you need emergency extra light and have no softer option.'],viewfinder:['BACK • VIEWFINDER','Optical viewfinder','Use it to compose and focus through the DSLR optical system.','Great for normal shooting, action, and bright outdoor scenes.'],lcd:['BACK • DISPLAY','Rear LCD','Use it for menus, reviewing photos, settings, and Live View.','Check important shots for focus and exposure instead of reviewing every frame.'],modeDial:['TOP • MODE DIAL','Mode dial','A+ is automatic, Av controls aperture, Tv controls shutter speed, and M is manual.','Stay in Av while learning. Use Tv when movement matters.'],shutter:['TOP • SHUTTER','Shutter button','Half-press to focus and meter. Press fully to take the photo.','Make the half-press before each shot a habit.']};

let camAngle=-20,startX=null,startAngle=-20;const cam=$('#camera3d'),stage=$('#cameraStage'),rot=$('#rotateSlider'),rotVal=$('#rotateValue');
function setCamAngle(a){camAngle=Math.max(-180,Math.min(180,a));if(cam)cam.style.transform=`rotateX(-8deg) rotateY(${camAngle}deg)`;if(rot)rot.value=camAngle;if(rotVal)rotVal.textContent=Math.round(camAngle)+'°'}
if(rot)rot.oninput=()=>setCamAngle(Number(rot.value));$$('.view-btn').forEach(b=>b.onclick=()=>setCamAngle(Number(b.dataset.angle)));
if(stage){stage.addEventListener('pointerdown',e=>{startX=e.clientX;startAngle=camAngle;stage.setPointerCapture?.(e.pointerId)});stage.addEventListener('pointermove',e=>{if(startX!==null)setCamAngle(startAngle+(e.clientX-startX)*.55)});stage.addEventListener('pointerup',()=>startX=null);stage.addEventListener('pointercancel',()=>startX=null)}

let seenControls={};try{seenControls=JSON.parse(localStorage.getItem('canonSeenControls')||'{}')}catch{}
$$('.hotspot').forEach(h=>h.onclick=e=>{e.stopPropagation();$$('.hotspot').forEach(x=>x.classList.remove('active'));h.classList.add('active');const d=cameraInfo[h.dataset.control];$('#controlTag').textContent=d[0];$('#controlTitle').textContent=d[1];$('#controlDesc').textContent=d[2];$('#controlWhen').textContent=d[3];seenControls[h.dataset.control]=true;try{localStorage.setItem('canonSeenControls',JSON.stringify(seenControls))}catch{}refreshProgress()});

const aps=[3.5,4,5.6,8,11,16],shutters=[30,60,125,250,500,1000],isos=[100,200,400,800,1600,3200,6400];const apS=$('#apSlider'),shS=$('#shSlider'),isoS=$('#isoSlider');
function updateSim(){if(!apS)return;const ap=aps[+apS.value],den=shutters[+shS.value],iso=isos[+isoS.value];const ratio=(iso/400)*(125/den)*Math.pow(5.6/ap,2),ev=Math.log2(ratio);$('#apVal').textContent='f/'+ap;$('#shVal').textContent='1/'+den;$('#isoVal').textContent='ISO '+iso;$('#simReadout').textContent=`f/${ap} • 1/${den} • ISO ${iso}`;const meter=$('#meter');meter.textContent=(ev>=0?'+':'')+ev.toFixed(1)+' EV';meter.className=Math.abs(ev)<=.5?'good':Math.abs(ev)<=1.5?'warn':'bad';$('#simScene').style.filter=`brightness(${Math.max(.35,Math.min(2.1,Math.pow(2,ev*.42)))})`;$('#simBg').style.filter=`blur(${Math.max(0,(8-ap)*1.3)}px)`;$('#motionGhost').style.opacity=den<=60?String(.5-(den-30)/120):den===125?'.08':'0';$('#noise').style.opacity=String(Math.min(.38,Math.max(0,Math.log2(iso/100)*.055)));let title='Balanced starting point.',body='Change one control at a time and watch what changes.';if(ev<-1.2){title='The image is getting dark.';body='Lower the f-number, slow the shutter, or raise ISO.'}else if(ev>1.2){title='The image is getting bright.';body='Raise the f-number, use a faster shutter, or lower ISO.'}else if(den<=60){title='Motion may blur.';body='Use a faster shutter for moving subjects.'}else if(iso>=3200){title='ISO noise is increasing.';body='This can still be better than a blurry photo.'}else if(ap<=4){title='Wide-aperture look.';body='The background becomes softer and more light enters.'}$('#simExplain').innerHTML=`<b>${title}</b><p>${body}</p>`}
[apS,shS,isoS].forEach(x=>x&&(x.oninput=updateSim));const preset={portrait:[0,2,1],action:[1,5,3],lowlight:[0,1,4],reset:[2,2,2]};let seenPresets={};try{seenPresets=JSON.parse(localStorage.getItem('canonSeenPresets')||'{}')}catch{}
$$('.sim-preset').forEach(b=>b.onclick=()=>{const p=preset[b.dataset.preset];apS.value=p[0];shS.value=p[1];isoS.value=p[2];if(b.dataset.preset!=='reset')seenPresets[b.dataset.preset]=true;try{localStorage.setItem('canonSeenPresets',JSON.stringify(seenPresets))}catch{}updateSim();refreshProgress()});updateSim();

const focal=$('#focalSlider');function updateFocal(){if(!focal)return;const mm=+focal.value;$('#focalReadout').textContent=mm+'mm';$('#focalLabelSvg').textContent=mm+'mm';const half=210-((mm-18)/37)*145;$('#fovCone').setAttribute('points',`113,136 555,${136-half} 555,${136+half}`);$('#focalDescSvg').textContent=mm<=24?'Wide scene — rooms, buildings, travel, groups':mm<48?'Natural everyday framing — street, food, cars':'Tighter framing — portraits and product detail'}if(focal)focal.oninput=updateFocal;updateFocal();

const angleData={eye:{title:'Eye Level',desc:'Neutral, natural, and easy to use',note:'<b>Eye level:</b> the safest starting angle for people.',cam:'translate(95,120)',line:[157,140,356,128]},high:{title:'High Angle',desc:'Softer, smaller, or more casual',note:'<b>High angle:</b> useful for food, desk setups, softer portraits, and showing more background.',cam:'translate(95,55)',line:[157,75,356,122]},low:{title:'Low Angle',desc:'Stronger and more dramatic',note:'<b>Low angle:</b> good for cars, buildings, action, and dramatic portraits.',cam:'translate(95,205)',line:[157,225,356,142]},overhead:{title:'Overhead',desc:'Graphic top-down look',note:'<b>Overhead:</b> excellent for products, food, desks, and flat lays.',cam:'translate(320,55) rotate(90)',line:[320,95,390,105]}};
$$('.angle-btn').forEach(b=>b.onclick=()=>{$$('.angle-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');const d=angleData[b.dataset.angleType],l=$('#angleLine');$('#angleCamera').setAttribute('transform',d.cam);['x1','y1','x2','y2'].forEach((a,i)=>l.setAttribute(a,d.line[i]));$('#angleTitleSvg').textContent=d.title;$('#angleDescSvg').textContent=d.desc;$('#angleNote').innerHTML=d.note});

const shots={portrait:['Portrait guide',['55mm','Av • f/5.6','ISO 100–400','Focus on nearest eye'],'Move the subject farther from the background for more blur.'],product:['Product guide',['35–55mm','Av • f/5.6–f/8','ISO 100–400','Use soft window light'],'Clean the background and the product before you shoot.'],landscape:['Landscape guide',['18–24mm','Av • f/8','ISO 100','Keep horizon straight'],'Add a foreground object to create depth.'],action:['Action guide',['Tv mode','1/500–1/1000 sec','Auto ISO','Track the subject'],'A slightly noisy sharp photo beats a clean blurry photo.'],indoor:['Indoor guide',['Av mode','Widest aperture','ISO 800–1600','Find a window'],'If people look blurry, your shutter is probably too slow.'],night:['Night guide',['Tripod','M • ISO 100','Try f/8','2-second timer'],'Start around 1–2 seconds and adjust from there.']};
function renderShot(key){const d=shots[key];$('#shotTitle').textContent=d[0];$('#shotSummary').innerHTML='<div class="pill-row">'+d[1].map(x=>`<span class="pill">${x}</span>`).join('')+'</div>';$('#shotSettings').innerHTML=d[1].map((x,i)=>`<div class="task"><span class="num">${i+1}</span><b>${x}</b></div>`).join('');$('#shotTip').innerHTML='<b>Remember:</b> '+d[2]}$$('.shot-choice').forEach(b=>b.onclick=()=>renderShot(b.dataset.shot));renderShot('portrait');

const fs=$('#finderSubject'),fl=$('#finderLight'),fm=$('#finderMotion');function updateFinder(){if(!fs)return;const subject=fs.value,light=fl.value,motion=fm.value;let mode='Av',lens='35mm',exp='f/5.6',iso='100–400',tip='Keep the background clean and focus deliberately.';if(subject==='portrait'){lens='50–55mm';exp='f/5.6';tip='Focus on the nearest eye and move the subject away from the background.'}if(subject==='product'){lens='35–55mm';exp='f/5.6–f/8';tip='Use soft window light and keep the product/background clean.'}if(subject==='landscape'){lens='18–24mm';exp='f/8';tip='Keep the horizon straight and add foreground depth.'}if(subject==='action'||motion==='fast'){mode='Tv';exp=motion==='fast'?'1/1000':'1/500';tip='Protect shutter speed first. A sharp noisy photo beats a clean blurry one.'}if(motion==='slow'&&subject!=='action'){mode='Tv';exp='1/250'}if(light==='bright')iso='100–200';if(light==='normal')iso='100–400';if(light==='indoor'){iso='800–1600';if(mode==='Av')tip+=' Watch that shutter speed does not get too slow.'}if(light==='night'){iso=(subject==='landscape'||subject==='product')?'100 on tripod':'1600–3200';if(subject==='landscape'){mode='M';exp='f/8 • 1–2s';tip='Use a tripod and the 2-second timer.'}}$('#findMode').textContent=mode;$('#findLens').textContent=lens;$('#findExposure').textContent=exp;$('#findIso').textContent=iso;$('#findTip').textContent=tip}[fs,fl,fm].forEach(x=>x&&(x.onchange=updateFinder));updateFinder();

let practiceState=[];try{practiceState=JSON.parse(localStorage.getItem('canonPracticeV5')||'[]')}catch{}const boxes=$$('#practice input[type=checkbox]');boxes.forEach((b,i)=>{if(practiceState[i])b.checked=true;b.onchange=()=>{savePractice();refreshProgress()}});function savePractice(){try{localStorage.setItem('canonPracticeV5',JSON.stringify(boxes.map(x=>x.checked)))}catch{}}
function refreshProgress(){const c=Object.keys(seenControls).length,p=Object.keys(seenPresets).length,done=boxes.filter(x=>x.checked).length,pct=boxes.length?Math.round(done/boxes.length*100):0;$('#prog').style.width=pct+'%';$('#progText').textContent=pct+'% complete';$('#practicePct').textContent=pct+'%';$('#controlsSeen').textContent=c+'/8';$('#simSeen').textContent=p+'/3';let title='Explore the camera',desc='Start with the physical controls you will touch most often.',href='#camera';if(c>=4&&p<2){title='Use the exposure simulator';desc='See aperture, shutter, and ISO change the photo.';href='#simulator'}else if(c>=4&&p>=2&&done<3){title='Complete a practice challenge';desc='Turn the visual lessons into a real shooting habit.';href='#practice'}else if(c>=4&&p>=2&&done>=3){title='Shoot and edit a real photo';desc='Use a shooting recipe, then finish the result.';href='#shoot'}$('#nextStep').textContent=title;const total=Math.round((Math.min(c,8)/8)*35+(Math.min(p,3)/3)*20+(done/Math.max(1,boxes.length))*45);$('#homePct').textContent=total+'%';$('#homeRing').style.setProperty('--pct',total);$('#homeControls').textContent=c+' / 8 explored';$('#homeSimulator').textContent=p+' / 3 tried';$('#homePractice').textContent=done+' / '+boxes.length+' complete';$('#homeNextTitle').textContent=title;$('#homeNextDesc').textContent=desc;$('#homeContinue').href=href}refreshProgress();

if('serviceWorker' in navigator&&(location.protocol==='https:'||location.hostname==='localhost'))window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
})();