(()=>{
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],camera=$('#camera');
  if(!camera||camera.dataset.cameraV2)return;camera.dataset.cameraV2='1';camera.classList.add('camera-v2');

  const essentials=['modeDial','shutter','mainDial','q','iso','af','afPoint','avComp'];
  const controls={
    modeDial:{view:'top',n:1,name:'Mode Dial',where:'Top-right shoulder of the camera',desc:'Chooses the shooting mode. For learning, the important positions are A+, Av, Tv and M.',steps:[['Rotate the dial','Line the mode you want up with the white index mark.'],['Start with Av','Av lets you choose aperture while the T7 chooses shutter speed.'],['Use Tv for motion','Tv lets you choose shutter speed when freezing movement matters.']],tip:'Use Av for portraits, products and everyday still photos. Move to Tv when the shutter speed itself is the priority.',core:true},
    shutter:{view:'top',n:2,name:'Shutter Button',where:'Front edge of the right-hand grip',desc:'This is a two-stage button: half-press first, then press fully.',steps:[['Half-press','The camera meters the scene and normally activates autofocus.'],['Wait for focus','Watch for focus confirmation in the viewfinder.'],['Press fully','Take the photograph without stabbing or jerking the button.']],tip:'Build the half-press habit. It is one of the most important DSLR habits for a beginner.',core:true},
    mainDial:{view:'top',n:3,name:'Main Dial',where:'Small ridged wheel just behind the shutter button',desc:'Changes the main exposure value for the shooting mode you are using.',steps:[['In Av','Turn it to change aperture / f-number.'],['In Tv','Turn it to change shutter speed.'],['In M','Turn it for shutter speed; hold Av ± while turning it to change aperture.']],tip:'If a recommendation says f/5.6 in Av, this is the wheel you turn.',core:true},
    flash:{view:'top',n:4,name:'Flash Button',where:'Beside the Mode Dial on the top-right shoulder',desc:'Raises the built-in flash in compatible Creative Zone shooting modes.',steps:[['Press the flash button','The built-in flash pops up when the current mode allows it.'],['Take a test shot','Direct flash can be useful but often looks harsher than window or bounced light.']],tip:'Learn natural light first. Use the built-in flash when you actually need extra light rather than leaving it up all the time.'},
    q:{view:'back',n:1,name:'Q · Quick Control',where:'Right side of the rear LCD, above the cross keys',desc:'Opens the Quick Control screen so you can change several shooting settings without digging through menus.',steps:[['Press Q','The current shooting settings become selectable on the LCD.'],['Move the highlight','Use the cross keys to choose the setting you want.'],['Press SET','Open that setting, choose the value, then confirm.']],tip:'When you do not remember which dedicated button changes a setting, Q is a very useful fallback.',core:true},
    iso:{view:'back',n:2,name:'ISO',where:'Top direction of the rear cross-key pad',desc:'Changes sensor sensitivity. Higher ISO helps maintain shutter speed in lower light but can add noise.',steps:[['Press ISO','Use the upper cross key labelled ISO.'],['Choose a value','Use the cross keys to choose AUTO or an ISO value.'],['Press SET','Confirm, then half-press the shutter to return to shooting.']],tip:'Do not be afraid to raise ISO when the alternative is motion blur or camera shake.',core:true},
    af:{view:'back',n:3,name:'AF Operation',where:'Right direction of the rear cross-key pad',desc:'Chooses how autofocus behaves: One-Shot, AI Focus or AI Servo.',steps:[['Press AF','Use the right cross key labelled AF.'],['Choose One-Shot','Use this for a subject that is not moving toward or away from you.'],['Choose AI Servo','Use this when you need the camera to keep updating focus on movement.']],tip:'For portraits and products, One-Shot is the cleanest starting point. For action, use AI Servo.',core:true},
    afPoint:{view:'back',n:4,name:'AF Point Selection',where:'Upper-right rear button near the viewfinder',desc:'Lets you choose which of the T7’s nine viewfinder AF points will be responsible for focus.',steps:[['Press the AF-point button','The AF points appear on the LCD / in the viewfinder.'],['Choose one point','Use the cross keys to move to the point you want.'],['Place it deliberately','For a portrait, put the chosen point on the nearest eye.']],tip:'Manual AF-point selection gives you more control than letting the camera choose the subject automatically.',core:true},
    avComp:{view:'back',n:5,name:'Av ± Button',where:'Upper-right side of the LCD, above the Q button',desc:'This button is used for exposure compensation in P/Tv/Av and for aperture control in Manual mode.',steps:[['For exposure compensation','In P, Tv or Av, hold Av ± and turn the Main Dial to make the camera’s automatic exposure brighter or darker.'],['For Manual aperture','In M mode, hold Av ± while turning the Main Dial to change aperture.']],tip:'If bright sky or reflections are blowing out, try a small negative exposure compensation such as −1/3 or −2/3 EV.',core:true},
    liveView:{view:'back',n:6,name:'Live View Button',where:'Immediately to the right of the viewfinder',desc:'Switches from the optical viewfinder to live image display on the rear LCD.',steps:[['Press Live View','The mirror moves and the scene appears on the LCD.'],['Compose on screen','Useful for tripod work, unusual angles and careful static composition.'],['Press again','Return to normal optical-viewfinder shooting.']],tip:'The optical viewfinder is usually the simpler choice for normal handheld photography and moving subjects.'},
    drive:{view:'back',n:7,name:'Drive / Self-timer',where:'Left direction of the rear cross-key pad',desc:'Chooses single shooting, continuous shooting or self-timer behavior.',steps:[['Press Drive / timer','Use the left cross key.'],['Choose the drive icon','Single for normal shooting, Continuous for sequences, or timer when you need a delay.'],['Press SET','Confirm the drive mode.']],tip:'The 2-second self-timer is very useful for tripod shots because you are not touching the camera during the exposure.'},
    wb:{view:'back',n:8,name:'White Balance',where:'Bottom direction of the rear cross-key pad',desc:'Changes how the camera interprets the colour of the light.',steps:[['Press WB','Use the lower cross key labelled WB.'],['Choose the light type','Auto works well while learning; Daylight, Shade and Tungsten are useful when you want predictable colour.'],['Press SET','Confirm your choice.']],tip:'Keep Auto WB while learning exposure unless the colour is clearly wrong. Change one variable at a time.'},
    lensZoom:{view:'lens',n:1,name:'18–55mm Zoom Ring',where:'Large ridged ring with the 18 · 24 · 35 · 55 markings',desc:'Changes framing and perspective by changing focal length.',steps:[['18mm','Wide field of view for rooms, buildings and broad scenes.'],['35mm','Natural general-purpose framing.'],['50–55mm','Tighter framing that works well for portraits and product detail.']],tip:'Zoom with the lens ring rather than walking only with your feet—the focal length also changes how the scene feels.'},
    lensAf:{view:'lens',n:2,name:'AF / MF Switch',where:'Small switch on the side of the 18–55mm lens',desc:'Chooses autofocus or manual focusing.',steps:[['Set AF','Keep it on AF for normal beginner shooting.'],['Use MF deliberately','Switch to MF only when you intentionally want to focus by hand.']],tip:'Do not rotate the focus ring aggressively while the lens is set to AF.'},
    stabilizer:{view:'lens',n:3,name:'Image Stabilizer',where:'ON / OFF switch directly below the AF/MF switch',desc:'Optical stabilization helps reduce blur from small hand movements.',steps:[['Handheld','Keep Stabilizer ON for normal handheld photography.'],['Stable tripod','It can be switched OFF when the camera is firmly locked on a tripod.']],tip:'Stabilization helps camera shake; it cannot freeze a moving person or car. Shutter speed handles subject movement.'}
  };

  let seen={};try{seen=JSON.parse(localStorage.getItem('canonSeenControls')||'{}')}catch{}
  const legacy={grip:'shutter',lens:'lensZoom',afmf:'lensAf',viewfinder:'q',lcd:'q'};Object.entries(legacy).forEach(([old,n])=>{if(seen[old])seen[n]=true});
  let view='back',selected='q',tourIndex=-1;

  camera.innerHTML=`
    <div class="cv3-hero"><div><small>EOS REBEL T7 · PHYSICAL CONTROLS</small><h1>Learn the camera in your hands.</h1><p>Tap a numbered control, find the same control on your Rebel T7, then follow the exact steps. This schematic follows the T7 control layout rather than pretending to be a decorative 3D model.</p></div><div class="cv3-progress"><b id="cv3Count">0 / 8</b><span>essentials explored</span></div></div>
    <div class="cv3-tabs"><button class="cv3-tab active" data-view="back">Back controls</button><button class="cv3-tab" data-view="top">Top controls</button><button class="cv3-tab" data-view="lens">18–55mm lens</button></div>
    <div class="cv3-layout">
      <div class="cv3-stage"><div class="cv3-stage-head"><b id="cv3ViewTitle">Back of camera</b><span>Tap a numbered control</span></div><div class="cv3-camera" id="cv3Camera" data-view="back"></div><div class="cv3-camera-hint">The drawing is a control map, not a scale 3D model.</div><div class="cv3-controls-list" id="cv3List"></div></div>
      <aside class="cv3-detail"><span class="cv3-detail-kicker" id="cv3Kicker">CONTROL 1</span><h2 id="cv3Name">Q · Quick Control</h2><p id="cv3Desc"></p><div class="cv3-where"><small>FIND IT</small><b id="cv3Where"></b></div><div class="cv3-steps" id="cv3Steps"></div><div class="cv3-tip" id="cv3Tip"></div><div class="cv3-detail-actions"><a class="button" href="#shoot">Use in Guided Shoot</a><button class="button primary" id="cv3Next">Next control</button></div></aside>
    </div>
    <div class="cv3-lower"><div class="cv3-tour"><small>5-MINUTE STARTER TOUR</small><h3>Learn the eight controls that matter first.</h3><p>Mode Dial → Shutter → Main Dial → Q → ISO → AF → AF point → Av ±. The app remembers what you have explored.</p><span class="cv3-tour-counter" id="cv3TourState">Not started</span><div class="cv3-tour-actions"><button class="button primary" id="cv3Tour">Start tour</button><button class="button" id="cv3Reset">Reset control progress</button></div></div><div class="cv3-reference"><small>KEEP THESE DEFAULTS WHILE LEARNING</small><h3>Simple starting setup</h3><div class="cv3-reference-grid"><div class="cv3-ref"><b>Lens AF</b><small>AF</small></div><div class="cv3-ref"><b>Stabilizer</b><small>ON handheld</small></div><div class="cv3-ref"><b>Image quality</b><small>Large / Fine JPEG</small></div><div class="cv3-ref"><b>Everyday mode</b><small>Av</small></div></div><div class="cv3-source">Control names and camera capabilities checked against Canon’s EOS Rebel T7 documentation.</div></div></div>`;

  const cam=$('#cv3Camera'),titles={back:'Back of camera',top:'Top of camera',lens:'18–55mm lens'};
  function drawing(){
    if(view==='back')return`<div class="cv3-viewfinder"></div><div class="cv3-back-grip"></div><div class="cv3-cross"><span class="cv3-cross-set">SET</span></div>`;
    if(view==='top')return`<div class="cv3-top-body"></div><div class="cv3-top-hump"></div><div class="cv3-hotshoe"></div><div class="cv3-lens-mount"></div><div class="cv3-mode-wheel"></div><div class="cv3-shutter-shape"></div><div class="cv3-main-wheel"></div>`;
    return`<div class="cv3-lens-body"></div><div class="cv3-lens-ring"></div><div class="cv3-lens-label">18 · 24 · 35 · 55</div><div class="cv3-switch-bank"><div class="cv3-switch">AF · MF</div><div class="cv3-switch">STABILIZER ON · OFF</div></div>`;
  }
  function viewControls(){return Object.entries(controls).filter(([,d])=>d.view===view)}
  function save(){try{localStorage.setItem('canonSeenControls',JSON.stringify(seen))}catch{}window.dispatchEvent(new CustomEvent('t7-camera-progress',{detail:{seen,count:essentials.filter(x=>seen[x]).length,total:essentials.length}}));window.T7Home?.refresh?.()}
  function progress(){$('#cv3Count').textContent=`${essentials.filter(x=>seen[x]).length} / ${essentials.length}`}
  function renderStage(){
    cam.dataset.view=view;cam.innerHTML=drawing()+viewControls().map(([id,d])=>`<button class="cv3-hotspot${id===selected?' active':''}${seen[id]?' seen':''}" data-id="${id}" aria-label="${d.name}">${d.n}</button>`).join('');$('#cv3ViewTitle').textContent=titles[view];
    $('#cv3List').innerHTML=viewControls().map(([id,d])=>`<button class="cv3-control-chip${id===selected?' active':''}" data-control="${id}"><small>${d.core?'ESSENTIAL':'REFERENCE'} · ${d.n}</small><b>${d.name}</b></button>`).join('');
    $$('.cv3-hotspot').forEach(b=>b.onclick=()=>select(b.dataset.id,true));$$('.cv3-control-chip').forEach(b=>b.onclick=()=>select(b.dataset.control,true));
  }
  function detail(id){
    const d=controls[id];if(!d)return;$('#cv3Kicker').textContent=`${d.core?'ESSENTIAL':'CONTROL'} · ${d.n}`;$('#cv3Name').textContent=d.name;$('#cv3Desc').textContent=d.desc;$('#cv3Where').textContent=d.where;$('#cv3Steps').innerHTML=d.steps.map((s,i)=>`<div class="cv3-step"><i>${i+1}</i><div><b>${s[0]}</b><span>${s[1]}</span></div></div>`).join('');$('#cv3Tip').textContent=d.tip;
  }
  function select(id,mark=false){const d=controls[id];if(!d)return;selected=id;if(view!==d.view){view=d.view;$$('.cv3-tab').forEach(x=>x.classList.toggle('active',x.dataset.view===view))}if(mark&&d.core){seen[id]=true;save()}detail(id);renderStage();progress()}
  function setView(v){view=v;const first=viewControls()[0]?.[0];if(first)selected=first;$$('.cv3-tab').forEach(x=>x.classList.toggle('active',x.dataset.view===view));renderStage();detail(selected)}
  $$('.cv3-tab').forEach(b=>b.onclick=()=>setView(b.dataset.view));
  $('#cv3Next').onclick=()=>{const current=Math.max(0,essentials.indexOf(selected)),next=essentials[(current+1)%essentials.length];select(next,true)};
  $('#cv3Tour').onclick=()=>{tourIndex=(tourIndex+1)%essentials.length;select(essentials[tourIndex],true);$('#cv3TourState').textContent=`${tourIndex+1} of ${essentials.length} · ${controls[essentials[tourIndex]].name}`;$('#cv3Tour').textContent=tourIndex===essentials.length-1?'Finish tour':'Next tour control'};
  $('#cv3Reset').onclick=()=>{if(!confirm('Reset the eight Camera Controls exploration checks?'))return;essentials.forEach(k=>delete seen[k]);tourIndex=-1;$('#cv3TourState').textContent='Not started';$('#cv3Tour').textContent='Start tour';save();renderStage();progress()};

  function pendingControl(){const p=window.T7Store?.getSession?.('cameraHelp');if(!p)return null;const map={mode:'modeDial',lens:'lensZoom',iso:'iso',af:'af',drive:'drive',exposure:'mainDial'};return controls[map[p]]?map[p]:null}
  window.addEventListener('t7-route-changed',e=>{if(e.detail?.route!=='camera')return;const p=pendingControl();if(p){select(p,true);window.T7Store?.setSession?.('cameraHelp',null)}});

  const pending=pendingControl();if(pending){selected=pending;view=controls[pending].view}else selected='q';renderStage();detail(selected);progress();save();
  window.T7CameraControls={select,controls,essentials};
})();