(()=>{const $=s=>document.querySelector(s);const input=$('#photoLocation'),status=$('#photoWeatherStatus');if(!input||!status)return;
function fmtTime(iso){if(!iso)return'—';const d=new Date(iso);return isNaN(d)?String(iso).split('T')[1]||iso:d.toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}
function shift(iso,min){const d=new Date(iso);d.setMinutes(d.getMinutes()+min);return d.toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}
function condition(code){if(code===0)return'Clear sky';if(code<=3)return'Partly cloudy';if(code===45||code===48)return'Fog';if(code>=51&&code<=67)return'Rain / drizzle';if(code>=71&&code<=77)return'Snow';if(code>=80&&code<=82)return'Showers';if(code>=95)return'Thunderstorm';return'Mixed weather'}
function advice(cur,daily){const cloud=Number(cur.cloud_cover||0),wind=Number(cur.wind_speed_10m||0),rain=Number((daily.precipitation_probability_max||[0])[0]||0);let title='Good general shooting conditions',text='Use the light you have and adjust exposure as needed.',pills=['Av mode','ISO 100–400'];if(rain>=60){title='Wet-weather opportunity';text='Rain is likely. Protect the camera from moisture, but reflections, wet streets, and dramatic skies can make strong photos.';pills=['1/250+ handheld','ISO 400–1600','Protect the camera']}else if(cloud>=75){title='Soft-light conditions';text='Heavy cloud acts like a giant diffuser. This is excellent for portraits and products because shadows are softer.';pills=['Portrait: 55mm','Av • f/5.6','ISO 200–800']}else if(cloud>=30){title='Very usable mixed light';text='Partial cloud gives softer light with some direction and texture in the sky. This works well for portraits, landscapes, and street photography.';pills=['Av mode','ISO 100–400','Watch changing exposure']}else{title='Bright direct-light conditions';text='Clear skies can create harsh midday shadows. Look for open shade, backlight, or shoot closer to golden hour.';pills=['ISO 100','1/250+','Use shade for portraits']}if(wind>=25){text+=' Wind is fairly strong, so use a faster shutter if hair, clothing, leaves, or handheld stability matter.';pills.push('1/500 for movement')}return{title,text,pills}}
function render(name,data){const cur=data.current||{},daily=data.daily||{};$('#weatherResults').hidden=false;$('#wcTemp').textContent=Math.round(cur.temperature_2m)+'°C';$('#wcCloud').textContent=Math.round(cur.cloud_cover||0)+'%';$('#wcWind').textContent=Math.round(cur.wind_speed_10m||0)+' km/h';$('#wcRain').textContent=Math.round((daily.precipitation_probability_max||[0])[0]||0)+'%';const rise=(daily.sunrise||[])[0],set=(daily.sunset||[])[0];$('#wcRise').textContent=fmtTime(rise);$('#wcSet').textContent=fmtTime(set);$('#goldenAM').textContent=rise?fmtTime(rise)+' – '+shift(rise,60):'—';$('#goldenPM').textContent=set?shift(set,-60)+' – '+fmtTime(set):'—';const a=advice(cur,daily);$('#photoAdviceTitle').textContent=a.title;$('#photoAdviceText').textContent=a.text+' Current condition: '+condition(Number(cur.weather_code||0))+'.';$('#photoSettingsPills').innerHTML=a.pills.map(x=>`<span class="pill">${x}</span>`).join('');status.textContent='Live conditions for '+name}
function forecast(lat,lon,name){status.textContent='Loading live conditions…';const url='https://api.open-meteo.com/v1/forecast?latitude='+encodeURIComponent(lat)+'&longitude='+encodeURIComponent(lon)+'&current=temperature_2m,cloud_cover,wind_speed_10m,weather_code&daily=sunrise,sunset,precipitation_probability_max&timezone=auto&forecast_days=1';fetch(url).then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>render(name,d)).catch(()=>status.textContent='Could not load weather right now. Try again.')}
function search(){const q=input.value.trim();if(!q){status.textContent='Type a city first.';return}status.textContent='Finding '+q+'…';fetch('https://geocoding-api.open-meteo.com/v1/search?name='+encodeURIComponent(q)+'&count=1&language=en&format=json').then(r=>r.json()).then(d=>{if(!d.results?.length)throw Error();const x=d.results[0],name=x.name+(x.admin1?', '+x.admin1:'')+(x.country?', '+x.country:'');forecast(x.latitude,x.longitude,name)}).catch(()=>status.textContent='Location not found. Try another city.')}
$('#searchPhotoWeather').onclick=search;input.addEventListener('keydown',e=>{if(e.key==='Enter')search()});$('#usePhotoLocation').onclick=()=>{if(!navigator.geolocation){status.textContent='Location is not available in this browser.';return}status.textContent='Requesting your location…';navigator.geolocation.getCurrentPosition(p=>forecast(p.coords.latitude,p.coords.longitude,'your location'),()=>status.textContent='Location permission was not granted. Search by city instead.',{enableHighAccuracy:false,timeout:10000})};
})();

(()=>{const head=document.head;function style(href){if(document.querySelector(`link[href="${href}"]`))return;const l=document.createElement('link');l.rel='stylesheet';l.href=href;head.appendChild(l)}function script(src){if(document.querySelector(`script[src="${src}"]`))return;const s=document.createElement('script');s.src=src;s.async=false;document.body.appendChild(s)}style('./shoot-flow.css');style('./learn.css');style('./review-flow.css');script('./shoot-flow.js');script('./learn.js');script('./review-flow.js')})();