(()=>{const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const canvas=$('#canvas');if(!canvas)return;const ctx=canvas.getContext('2d',{willReadFrequently:true}),fileInput=$('#fileInput'),placeholder=$('#placeholder'),compareTag=$('#compareTag');let originalImage=null,originalCanvas=document.createElement('canvas'),rotation=0,splitMode=false,splitPct=50;const ids=['exposure','highlights','shadows','contrast','warmth','saturation','sharpness'];
const controls=$('#editorControls');controls.innerHTML=ids.map(id=>`<div class="editor-control"><label><span>${id[0].toUpperCase()+id.slice(1)}</span><b id="v-${id}">0</b></label><input id="${id}" type="range" min="${id==='sharpness'?0:-100}" max="100" value="0"></div>`).join('');
function vals(){const o={};ids.forEach(id=>o[id]=Number($('#'+id).value));return o}function labels(){ids.forEach(id=>$('#v-'+id).textContent=$('#'+id).value)}
function adjust(data,v){const d=data.data,exp=v.exposure*2,cont=(259*(v.contrast+255))/(255*(259-v.contrast)),sat=1+v.saturation/100,w=v.warmth/100,hi=v.highlights/100,sh=v.shadows/100;for(let i=0;i<d.length;i+=4){let r=d[i]+exp,g=d[i+1]+exp,b=d[i+2]+exp;r=cont*(r-128)+128;g=cont*(g-128)+128;b=cont*(b-128)+128;const lum=.2126*r+.7152*g+.0722*b;r=lum+(r-lum)*sat;g=lum+(g-lum)*sat;b=lum+(b-lum)*sat;r+=w*18;b-=w*18;const L=(r+g+b)/3;if(hi<0&&L>150){const f=((L-150)/105)*(-hi)*.55;r-=r*f;g-=g*f;b-=b*f}else if(hi>0&&L>150){const f=((L-150)/105)*hi*.35;r+=(255-r)*f;g+=(255-g)*f;b+=(255-b)*f}if(sh>0&&L<140){const f=((140-L)/140)*sh*.65;r+=(255-r)*f*.45;g+=(255-g)*f*.45;b+=(255-b)*f*.45}else if(sh<0&&L<140){const f=((140-L)/140)*(-sh)*.55;r-=r*f;g-=g*f;b-=b*f}d[i]=Math.max(0,Math.min(255,r));d[i+1]=Math.max(0,Math.min(255,g));d[i+2]=Math.max(0,Math.min(255,b))}return data}
function sharpen(data,amt){if(amt<=0)return data;const w=data.width,h=data.height,src=new Uint8ClampedArray(data.data),out=data.data,a=amt/100*.5;for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const idx=(y*w+x)*4;for(let c=0;c<3;c++){const center=src[idx+c],neighbors=src[idx-4+c]+src[idx+4+c]+src[idx-w*4+c]+src[idx+w*4+c];out[idx+c]=Math.max(0,Math.min(255,center*(1+4*a)-neighbors*a))}}return data}
function drawBase(){const swap=Math.abs(rotation)%180===90;canvas.width=swap?originalCanvas.height:originalCanvas.width;canvas.height=swap?originalCanvas.width:originalCanvas.height;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.save();ctx.translate(canvas.width/2,canvas.height/2);ctx.rotate(rotation*Math.PI/180);ctx.drawImage(originalCanvas,-originalCanvas.width/2,-originalCanvas.height/2);ctx.restore()}
function editedCopy(){drawBase();let d=ctx.getImageData(0,0,canvas.width,canvas.height),v=vals();d=adjust(d,v);d=sharpen(d,v.sharpness);ctx.putImageData(d,0,0);const c=document.createElement('canvas');c.width=canvas.width;c.height=canvas.height;c.getContext('2d').drawImage(canvas,0,0);return c}
function render(original=false){if(!originalImage)return;if(original){drawBase();compareTag.style.display='block';return}compareTag.style.display='none';if(splitMode){const edited=editedCopy();drawBase();const cut=Math.round(canvas.width*splitPct/100);ctx.save();ctx.beginPath();ctx.rect(cut,0,canvas.width-cut,canvas.height);ctx.clip();ctx.drawImage(edited,0,0);ctx.restore();ctx.fillStyle='rgba(255,255,255,.9)';ctx.fillRect(cut-1,0,2,canvas.height);return}editedCopy()}
function reset(){ids.forEach(id=>$('#'+id).value=0);labels();rotation=0;render(false)}
ids.forEach(id=>$('#'+id).oninput=()=>{labels();render(false)});fileInput.onchange=e=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=ev=>{const img=new Image();img.onload=()=>{originalImage=img;rotation=0;const maxW=1600,maxH=1200;let w=img.width,h=img.height,sc=Math.min(1,maxW/w,maxH/h);w=Math.round(w*sc);h=Math.round(h*sc);originalCanvas.width=w;originalCanvas.height=h;originalCanvas.getContext('2d').drawImage(img,0,0,w,h);ids.forEach(id=>$('#'+id).value=0);labels();placeholder.hidden=true;render(false)};img.src=ev.target.result};reader.readAsDataURL(file)};
$('#rotateLeft').onclick=()=>{if(originalImage){rotation=(rotation-90)%360;render(false)}};$('#rotateRight').onclick=()=>{if(originalImage){rotation=(rotation+90)%360;render(false)}};$('#resetBtn').onclick=reset;const cmp=$('#compareBtn');cmp.addEventListener('pointerdown',()=>render(true));['pointerup','pointerleave','pointercancel'].forEach(ev=>cmp.addEventListener(ev,()=>render(false)));$('#downloadBtn').onclick=()=>{if(!originalImage)return;const prev=splitMode;splitMode=false;render(false);const a=document.createElement('a');a.download='canon-t7-edited.jpg';a.href=canvas.toDataURL('image/jpeg',.94);a.click();splitMode=prev;render(false)};$('#splitBtn').onclick=()=>{splitMode=!splitMode;$('#splitControl').hidden=!splitMode;$('#splitBtn').textContent=splitMode?'Exit split compare':'Split before / after';render(false)};$('#splitSlider').oninput=e=>{splitPct=Number(e.target.value);render(false)};
const recipes={portrait:{exposure:10,highlights:-5,shadows:8,contrast:4,warmth:6,saturation:5,sharpness:8},product:{exposure:6,highlights:-3,shadows:4,contrast:12,warmth:0,saturation:6,sharpness:20},landscape:{exposure:0,highlights:-5,shadows:10,contrast:15,warmth:2,saturation:12,sharpness:15},night:{exposure:8,highlights:-10,shadows:12,contrast:5,warmth:0,saturation:0,sharpness:10}};$$('.recipe').forEach(b=>b.onclick=()=>{const r=recipes[b.dataset.recipe];Object.entries(r).forEach(([k,v])=>$('#'+k).value=v);labels();render(false)});labels();
})();