(()=>{
  if(window.T7PhotographyCourse)return;
  const $=s=>document.querySelector(s);
  const guide=$('#photographyGuide'),learn=$('#learn');
  if(!guide||!learn)return;
  const KEY='canonT7PhotographyCourseV1';
  const icon=name=>window.T7Icons?.icon?.(name)||document.createElement('span');
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

  const chapters=[
    {id:'control',num:'01',title:'Control the camera',level:'BEGINNER',desc:'Stop guessing what the camera is doing.',steps:[
      {id:'handling',title:'Camera handling & stability',time:'8 min',sub:'Build a sharp-photo baseline before changing settings.',understand:'Camera shake can make a perfectly focused photo look soft. Stable stance, gentle shutter pressure and a sensible shutter speed matter before anything advanced.',t7:'Keep lens Stabilizer ON for normal handheld shooting. Use the viewfinder, tuck your elbows in and half-press before smoothly taking the photo.',assignment:'Photograph the same detailed object three times handheld at 55mm. Concentrate only on stance, half-press focus and smooth shutter pressure.',inspect:'Zoom in afterward. Look for crisp lettering or edges. If all three are soft, compare shutter speed and focus before blaming the lens.',actions:[['Find T7 controls','route:camera'],['Start practice','route:practice']]},
      {id:'exposure',title:'The exposure triangle',time:'12 min',sub:'Aperture, shutter and ISO solve different problems.',understand:'Exposure is not three brightness sliders. Aperture changes depth of field, shutter changes motion, and ISO changes signal amplification. Choose the creative need first, then balance brightness.',t7:'Use Av when depth of field matters, Tv when motion matters, and M when you need both aperture and shutter to stay fixed.',assignment:'Use the Simulator. Make one bright exposure three different ways while deliberately changing aperture, shutter and ISO.',inspect:'Ask what changed besides brightness. Did the background blur, movement or noise change?',actions:[['Open aperture lesson','lesson:aperture'],['Use simulator','route:simulator']]},
      {id:'aperture',title:'Aperture & depth of field',time:'10 min',sub:'Control how much of the scene appears sharp.',understand:'A lower f-number means a larger opening and usually shallower depth of field. Subject distance, background distance and focal length matter just as much as the f-number.',t7:'With the 18–55mm kit lens, use the lowest available f-number. At 55mm that is typically f/5.6. Zoom longer and step back for stronger subject separation.',assignment:'Photograph one object at 55mm with space behind it. Compare the lowest f-number available with f/11.',inspect:'Compare the subject edges and the background. The point is not “more blur is always better”; it is learning to choose depth deliberately.',lesson:'aperture',actions:[['Open lesson','lesson:aperture'],['Shoot portrait','shoot:portrait']]},
      {id:'motioniso',title:'Shutter speed & ISO',time:'12 min',sub:'Protect sharpness when light or movement changes.',understand:'Shutter speed controls how long movement is recorded. ISO is often what lets you keep the shutter speed you actually need when light drops.',t7:'For still people start around 1/125. Walking people often need 1/250. Faster action may need 1/500–1/1000. Raise ISO when needed rather than accepting motion blur.',assignment:'Photograph a moving subject at roughly 1/60, 1/250 and 1/1000. Let ISO rise if necessary.',inspect:'Compare motion sharpness first, then noise. Decide which compromise produces the better photograph.',actions:[['Shutter lesson','lesson:shutter'],['ISO lesson','lesson:iso']]}
    ]},
    {id:'intent',num:'02',title:'Make the frame intentional',level:'BEGINNER+',desc:'Focus, focal length, composition and light.',steps:[
      {id:'focus',title:'Autofocus you can trust',time:'10 min',sub:'Choose what must be sharp before pressing the shutter.',understand:'Autofocus works best when you give the camera a clear target. A sharp background with a soft subject is usually a focus-choice problem, not an exposure problem.',t7:'For still subjects use One-Shot AF and select one AF point. Put it on the nearest eye for portraits or on a high-contrast detail for objects. Use AI Servo for moving subjects.',assignment:'Take three photos of an object with lettering using one AF point. Then repeat with automatic AF point selection.',inspect:'Compare which set places sharpness where you intended. Look at the exact detail you focused on, not the whole thumbnail.',lesson:'focus',actions:[['Focus lesson','lesson:focus'],['Find AF controls','route:camera']]},
      {id:'focal',title:'18mm vs 35mm vs 55mm',time:'10 min',sub:'Focal length changes perspective and visual emphasis.',understand:'Zoom is not only about making the subject bigger. Wide focal lengths include more environment; longer focal lengths make it easier to simplify the frame and can be more flattering for people.',t7:'Use roughly 18–24mm for wide scenes, 35mm for natural everyday framing, and 50–55mm for portraits, products and detail.',assignment:'Photograph the same subject at 18mm, 35mm and 55mm. Reposition yourself so the subject stays approximately the same size.',inspect:'Compare how the background and proportions change. Notice which version looks cleanest rather than only which looks closest.',lesson:'focal',actions:[['Lens lesson','lesson:focal'],['Open visual guides','route:visuals']]},
      {id:'composition',title:'Composition before settings',time:'12 min',sub:'Move your feet, simplify the frame, then expose it.',understand:'A technically perfect photo can still be weak if the frame has no clear subject. Composition is mainly deciding what belongs in the photograph and what does not.',t7:'Use the viewfinder edges deliberately. Before shooting, scan all four edges, check the background and decide whether the subject should be centered or offset.',assignment:'Make three versions of one scene: centered, rule-of-thirds, and a version using a leading line or foreground element.',inspect:'Choose the version where your eye knows immediately where to look. Identify one distraction you could remove next time.',lesson:'composition',actions:[['Composition lesson','lesson:composition'],['Start landscape shoot','shoot:landscape']]},
      {id:'light',title:'Read the light',time:'12 min',sub:'Direction and softness matter more than expensive gear.',understand:'Front light, side light and backlight create very different shape and contrast. Large soft light sources are flattering; small direct sources create harder shadows.',t7:'Use exposure compensation in Av/Tv when the camera makes the subject too bright or dark. Protect important highlights when the scene has strong contrast.',assignment:'Photograph the same object or person in open shade, direct sun and window light.',inspect:'Compare shadow hardness, skin/object texture and highlight detail. Decide which light makes the subject easiest to read.',actions:[['Check Conditions','route:conditions'],['Shoot portrait','shoot:portrait']]}
    ]},
    {id:'scenes',num:'03',title:'Photograph real subjects',level:'PRACTICAL',desc:'People, products, cars and difficult light.',steps:[
      {id:'portrait',title:'Portraits that feel natural',time:'15 min',sub:'Focal length, eye focus, distance and background.',understand:'A good portrait is usually built from flattering perspective, clear eye focus, simple background and light that shapes the face without distracting from it.',t7:'Start around 50–55mm, lowest available f-number, One-Shot AF and one AF point on the nearest eye. Protect roughly 1/125 or faster handheld.',assignment:'Take one portrait at 18mm close to the subject and another at 55mm after stepping back. Then make a third with a cleaner background.',inspect:'Compare facial proportions, background clutter and eye sharpness. Keep the frame that feels least distorted and most intentional.',actions:[['Portrait Guided Shoot','shoot:portrait'],['Review a portrait','route:review']]},
      {id:'product',title:'Cars & products',time:'15 min',sub:'Manage reflections, edges and highlight detail.',understand:'Shiny objects are mostly photographs of reflected light. Angle and environment often matter more than changing exposure settings.',t7:'Outdoors start near ISO 100 and roughly f/5.6–f/8 for a parked car or product. Use 35–55mm and watch bright reflections before pressing the shutter.',assignment:'Photograph a reflective object from three angles without moving the object. Try to reduce one distracting reflection using only your position.',inspect:'Check highlight clipping, straight edges, background distractions and whether the object shape is easy to understand.',actions:[['Car / product shoot','shoot:product'],['Open Editor','route:edit']]},
      {id:'harsh',title:'Harsh sun & high contrast',time:'12 min',sub:'Protect highlights and choose better angles.',understand:'Midday sun creates deep shadows and bright highlights that may exceed the camera’s usable range. Sometimes the best exposure fix is moving the subject or camera.',t7:'Use Av or Tv as needed and try modest negative exposure compensation when important highlights are clipping. Open shade often gives a better starting point for people.',assignment:'Photograph the same subject in direct sun and open shade. In direct sun, try a second exposure slightly darker.',inspect:'Compare skin/object highlights and shadow detail. Decide whether the darker exposure preserved important texture.',actions:[['Check current light','route:conditions'],['Open exposure lesson','lesson:aperture']]},
      {id:'flash',title:'Flash as controlled light',time:'12 min',sub:'Use flash to solve a lighting problem, not because the room is dark.',understand:'Direct on-camera flash can look flat because the light comes from almost the same direction as the lens. Flash becomes more useful when its power, distance or direction is controlled.',t7:'Start conservatively. Keep normal ambient exposure in mind and use flash to add light to the subject. If using a third-party slave flash, confirm its triggering mode and power manually rather than assuming TTL automation.',assignment:'Photograph one object without flash, then with direct flash. If your flash can be repositioned or bounced safely, make a third version with less direct light.',inspect:'Compare shadow direction, reflections and background brightness. The best version should look intentionally lit, not simply brighter.',actions:[['Open Camera guide','route:camera'],['Start indoor shoot','shoot:indoor']]}
    ]},
    {id:'motion',num:'04',title:'Handle movement & low light',level:'INTERMEDIATE',desc:'Action, panning, indoor scenes and night.',steps:[
      {id:'action',title:'Freeze action',time:'12 min',sub:'Prioritize shutter speed and continuous focus.',understand:'Action photography succeeds when shutter speed, focus tracking and timing work together. Burst rate cannot rescue poor timing.',t7:'Use Tv mode, AI Servo AF and roughly 1/500–1/1000 for fast movement. The T7 shoots at a modest burst rate, so anticipate the moment.',assignment:'Photograph a person, pet or vehicle moving across the frame at 1/250 and then 1/1000.',inspect:'Compare subject sharpness and ISO. Decide whether the faster shutter was worth the added noise.',actions:[['Action Guided Shoot','shoot:action'],['Shutter lesson','lesson:shutter']]},
      {id:'panning',title:'Panning for motion',time:'15 min',sub:'Keep the subject sharp while the background moves.',understand:'Panning deliberately uses a slower shutter while you rotate the camera to follow the subject. The technique communicates speed rather than freezing everything.',t7:'Try Tv mode around 1/30–1/125 depending on subject speed. Use AI Servo, follow smoothly before pressing the shutter and continue moving after the exposure.',assignment:'Track a moving car, bicycle or person across the frame. Make at least ten attempts at one shutter speed before changing it.',inspect:'Look for a relatively sharp subject with directional background blur. Judge consistency, not one lucky frame.',actions:[['Open simulator','route:simulator'],['Action shoot','shoot:action']]},
      {id:'indoor',title:'Indoor available light',time:'12 min',sub:'Use ISO to protect people and handheld sharpness.',understand:'Indoor light often forces a compromise. If people are involved, a faster shutter usually matters more than keeping ISO low.',t7:'For still people protect roughly 1/125. Start around ISO 800–1600 if needed, use the widest useful aperture and watch mixed-color lighting.',assignment:'Make the same indoor portrait at a low ISO/slow shutter and then a higher ISO/faster shutter.',inspect:'Zoom in on the eyes. Decide whether added noise is less damaging than motion blur.',actions:[['Indoor Guided Shoot','shoot:indoor'],['ISO lesson','lesson:iso']]},
      {id:'night',title:'Night handheld vs tripod',time:'15 min',sub:'Choose whether the camera or subject is allowed to move.',understand:'At night, the correct strategy depends on movement. A tripod helps camera shake but cannot freeze a moving person. Handheld scenes need enough shutter speed even if ISO becomes high.',t7:'Handheld still scenes can start near 1/60 with stabilization. People need faster speeds. On a tripod, use low ISO, disable unnecessary stabilization and use the self-timer to avoid touching the camera.',assignment:'Photograph one night scene handheld, then support the camera securely and make a lower-ISO slower exposure of the same scene.',inspect:'Compare noise, fine detail, moving objects and highlight clipping from lamps or signs.',actions:[['Night Guided Shoot','shoot:night'],['Check night conditions','route:conditions']]}
    ]},
    {id:'workflow',num:'05',title:'Build an intermediate workflow',level:'INTERMEDIATE',desc:'Metering, manual control, review and editing.',steps:[
      {id:'compensation',title:'Exposure compensation & highlights',time:'10 min',sub:'Correct the camera without abandoning Av/Tv.',understand:'Camera meters aim for a reasonable average, not your creative intent. Bright or dark scenes can fool that average. Exposure compensation is often faster than switching to Manual.',t7:'In Av/Tv, use exposure compensation when the preview/histogram shows the important subject consistently too bright or dark. Negative compensation helps protect highlights.',assignment:'Photograph a bright scene at 0 EV, -1/3 EV and -2/3 EV without changing composition.',inspect:'Compare highlight texture and shadow detail. Pick the brightest exposure that still preserves the highlights you care about.',actions:[['Use simulator','route:simulator'],['Review exposure','route:review']]},
      {id:'manual',title:'When Manual mode actually helps',time:'12 min',sub:'Lock exposure when consistency matters.',understand:'Manual mode is valuable when the light is stable and you want multiple frames to match, or when automated metering keeps changing because the subject/background shifts.',t7:'Choose aperture for depth, shutter for motion, then ISO for brightness. Watch the meter but judge the actual result and highlights—not the goal of always centering the meter.',assignment:'In one constant-light scene, set M mode and take three different compositions without changing exposure.',inspect:'Check whether brightness remains consistent even when the frame contains more bright or dark background.',actions:[['Open simulator','route:simulator'],['Start product shoot','shoot:product']]},
      {id:'review',title:'Review like a photographer',time:'12 min',sub:'Separate technical failure from creative preference.',understand:'Do not ask only whether you “like” the photo. Check focus, motion, exposure, highlight detail, composition and then the emotional/visual result.',t7:'Keep the original JPEG with EXIF when possible. The settings tell you what the camera actually did and make the next attempt measurable.',assignment:'Choose three recent photos. For each, write one technical strength, one technical weakness and one compositional change you would make.',inspect:'Look for a repeated pattern across the three frames. That repeated pattern should become your next practice drill.',actions:[['Open Review','route:review'],['Open Library','route:library']]},
      {id:'editing',title:'Edit to finish, not rescue',time:'15 min',sub:'Crop, tone and color should strengthen a good capture.',understand:'Editing works best when it clarifies the photograph’s intent. Heavy recovery cannot fully replace missing focus, clipped highlights or motion blur.',t7:'Capture the cleanest original you can, then make small deliberate adjustments: crop, exposure, highlights/shadows, white balance, contrast and detail.',assignment:'Edit one photo in two ways: a restrained natural version and a stronger stylized version. Do not change the crop between them.',inspect:'Compare which edit supports the subject better. If the edit draws attention to itself more than the photograph, reduce it.',actions:[['Open Editor','route:edit'],['Compare in Library','route:library']]}
    ]}
  ];

  const lessonMap={aperture:'aperture',motioniso:'shutter',focus:'focus',focal:'focal',composition:'composition'};
  let saved=read();
  function read(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');return x&&typeof x==='object'?x:{}}catch{return{}}}
  function write(){try{localStorage.setItem(KEY,JSON.stringify(saved))}catch{};window.dispatchEvent(new CustomEvent('t7-course-updated',{detail:{progress:progress()}}))}
  function legacyDone(){try{return JSON.parse(localStorage.getItem('canonLearnDone')||'{}')||{}}catch{return{}}}
  function isDone(step){if(saved[step.id])return true;const l=lessonMap[step.id]||step.lesson;return !!(l&&legacyDone()[l])}
  function allSteps(){return chapters.flatMap(c=>c.steps.map(s=>({...s,chapter:c})))}
  function progress(){const steps=allSteps(),done=steps.filter(isDone).length;return{done,total:steps.length,pct:Math.round(done/steps.length*100)}}
  function nextStep(){return allSteps().find(s=>!isDone(s))||null}
  function setLesson(key){try{localStorage.setItem('canonLearnActive',key)}catch{};location.hash='learn';setTimeout(()=>$('#learnList button[data-lesson="'+key+'"]')?.click(),80)}
  function setShoot(subject){window.T7Store?.set?.('shootSubject',subject);window.T7Store?.set?.('shootScene',null);try{localStorage.setItem('canonT7LastShootSubject',subject);localStorage.removeItem('canonT7LastScene')}catch{}location.hash='shoot'}
  function act(action){if(action.startsWith('lesson:'))return setLesson(action.split(':')[1]);if(action.startsWith('shoot:'))return setShoot(action.split(':')[1]);if(action.startsWith('route:')){location.hash=action.split(':')[1];return}}

  const course=document.createElement('section');course.className='photography-course';course.id='photographyCourse';
  const firstSection=guide.querySelector('.pg-section');
  guide.insertBefore(course,firstSection||null);

  function render(){
    const p=progress(),next=nextStep();
    course.innerHTML=`<div class="pc-head"><div><small>BEGINNER → INTERMEDIATE</small><h2>Your photography course</h2><p>Twenty practical checkpoints. Learn the idea, set the Rebel T7, make a photograph, then inspect what changed.</p></div><div class="pc-progress"><div class="pc-progress-ring" style="--pct:${p.pct}"><b>${p.pct}%</b></div><div class="pc-progress-copy"><b>${p.done} / ${p.total}</b><span>checkpoints complete</span></div></div></div>${next?`<div class="pc-current"><div class="pc-current-icon" id="pcCurrentIcon"></div><div><small>CONTINUE COURSE</small><b>${esc(next.title)}</b><span>${esc(next.chapter.title)} · ${esc(next.sub)}</span></div><button id="pcContinue">Continue</button></div>`:''}<div class="pc-chapters" id="pcChapters"></div><div class="pc-finish ${next?'':'show'}"><b>You completed the core course.</b><p>Now the useful work is repetition: shoot deliberately, review the actual settings, find a recurring weakness, and build a practice drill around it.</p></div>`;
    if(next){$('#pcCurrentIcon').appendChild(icon(next.chapter.id==='control'?'camera':next.chapter.id==='intent'?'guide':next.chapter.id==='scenes'?'portrait':next.chapter.id==='motion'?'action':'review'));$('#pcContinue').onclick=()=>openStep(next.chapter.id,next.id)}
    const host=$('#pcChapters');
    chapters.forEach((c,ci)=>{
      const done=c.steps.filter(isDone).length,complete=done===c.steps.length,containsNext=next?.chapter?.id===c.id;
      const wrap=document.createElement('article');wrap.className='pc-chapter'+(complete?' complete':'')+(containsNext?' active open':'');wrap.dataset.chapter=c.id;
      wrap.innerHTML=`<button class="pc-chapter-head"><span class="pc-chapter-num">${c.num}</span><span class="pc-chapter-copy"><small>${esc(c.level)}</small><b>${esc(c.title)}</b><span>${esc(c.desc)}</span></span><span class="pc-chapter-status"><i></i><span>${done}/${c.steps.length}</span></span></button><div class="pc-steps"></div>`;
      wrap.querySelector('.pc-chapter-head').onclick=()=>wrap.classList.toggle('open');
      const stepsHost=wrap.querySelector('.pc-steps');
      c.steps.forEach((s,si)=>stepsHost.appendChild(stepElement(c,s,si)));
      host.appendChild(wrap);
    });
  }

  function stepElement(c,s,index){
    const done=isDone(s),el=document.createElement('div');el.className='pc-step'+(done?' complete':'');el.dataset.step=s.id;
    el.innerHTML=`<button class="pc-step-main"><span class="pc-step-check">${done?'✓':String(index+1).padStart(2,'0')}</span><span class="pc-step-copy"><small>${esc(c.title)}</small><b>${esc(s.title)}</b><span>${esc(s.sub)}</span></span><span class="pc-step-time">${esc(s.time)}</span></button><div class="pc-step-detail"><div class="pc-detail-grid"><div class="pc-detail-card"><span class="pc-detail-label">UNDERSTAND</span><b>${esc(s.understand)}</b></div><div class="pc-detail-card"><span class="pc-detail-label">SET IT ON THE T7</span><b>${esc(s.t7)}</b></div><div class="pc-detail-card"><span class="pc-detail-label">TAKE THIS PHOTO</span><b>${esc(s.assignment)}</b></div><div class="pc-detail-card"><span class="pc-detail-label">LOOK FOR THIS</span><b>${esc(s.inspect)}</b></div></div><div class="pc-step-actions"></div></div>`;
    el.querySelector('.pc-step-main').onclick=()=>el.classList.toggle('open');
    const actions=el.querySelector('.pc-step-actions');
    (s.actions||[]).forEach(([label,action],i)=>{const b=document.createElement('button');b.textContent=label;if(i===0)b.classList.add('primary');b.onclick=()=>act(action);actions.appendChild(b)});
    const complete=document.createElement('button');complete.className='complete-action'+(done?' done':'');complete.textContent=done?'Completed ✓':'Mark checkpoint complete';complete.onclick=()=>{saved[s.id]=!isDone(s);if(!saved[s.id])delete saved[s.id];write();render();setTimeout(()=>openStep(c.id,s.id),20)};actions.appendChild(complete);
    return el;
  }
  function openStep(chapterId,stepId){const chapter=course.querySelector(`[data-chapter="${chapterId}"]`);if(!chapter)return;chapter.classList.add('open');const step=chapter.querySelector(`[data-step="${stepId}"]`);if(step){step.classList.add('open');step.scrollIntoView({behavior:'smooth',block:'center'})}}
  window.addEventListener('storage',e=>{if(e.key===KEY||e.key==='canonLearnDone'){saved=read();render()}});
  window.addEventListener('t7-route-changed',e=>{if(e.detail?.route==='learn')render()});
  render();
  window.T7PhotographyCourse={progress,nextStep,openStep,version:'1.0.0'};
})();
