(()=>{
  if(window.T7PhotographyGuide)return;
  const $=s=>document.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const learn=$('#learn');if(!learn)return;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const icon=name=>window.T7Icons?.icon?.(name)||document.createElement('span');

  const topics=[
    {id:'exposure',group:'start',icon:'aperture',title:'Exposure',eyebrow:'START HERE',desc:'Understand aperture, shutter speed and ISO as one system.',lesson:'aperture',color:'#ff9b78'},
    {id:'focus',group:'start',icon:'focus',title:'Focus',eyebrow:'SHARPNESS',desc:'Choose what must be sharp and make autofocus predictable.',lesson:'focus',color:'#91c7ff'},
    {id:'composition',group:'creative',icon:'guide',title:'Composition',eyebrow:'FRAMING',desc:'Make stronger pictures by changing position, background and edges.',lesson:'composition',color:'#b8a6ff'},
    {id:'light',group:'creative',icon:'sun',title:'Light',eyebrow:'SEE THE SCENE',desc:'Direction, softness and time of day matter more than expensive gear.',href:'#conditions',color:'#f0bf73'},
    {id:'lens',group:'creative',icon:'lens',title:'18–55mm Lens',eyebrow:'PERSPECTIVE',desc:'Know when to use 18mm, 35mm and 55mm—and when to move your feet.',lesson:'focal',color:'#9bd9bd'},
    {id:'portrait',group:'scenes',icon:'portrait',title:'Portraits',eyebrow:'PEOPLE',desc:'Flattering focal length, eye focus, background separation and light.',shoot:'portrait',color:'#ff9ba3'},
    {id:'product',group:'scenes',icon:'product',title:'Cars & Products',eyebrow:'DETAIL',desc:'Control reflections, highlights, angle and clean product detail.',shoot:'product',color:'#8fd2d5'},
    {id:'action',group:'scenes',icon:'action',title:'Action',eyebrow:'MOVEMENT',desc:'Freeze motion, track focus and learn when shutter speed matters most.',shoot:'action',lesson:'shutter',color:'#ffc06c'},
    {id:'night',group:'scenes',icon:'night',title:'Night & Indoor',eyebrow:'LOW LIGHT',desc:'Protect shutter speed, use ISO confidently and avoid unnecessary blur.',shoot:'night',lesson:'iso',color:'#9daaff'},
    {id:'editing',group:'editing',icon:'sliders',title:'Editing',eyebrow:'FINISH THE FRAME',desc:'Exposure, color, crop and detail—without trying to rescue a bad capture.',href:'#edit',color:'#b8d7a7'}
  ];

  const answers={
    'blurry':{title:'Why is my photo blurry?',body:'First decide whether the blur comes from camera movement, subject movement, or missed focus. For handheld people, protect roughly 1/125 or faster. For movement, start around 1/250–1/500. Then raise ISO if needed instead of accepting a shutter speed that is too slow.',actions:[['Open shutter lesson','lesson:shutter',true],['Start Guided Shoot','shoot:action',false]]},
    'background':{title:'How do I blur the background?',body:'Use a longer focal length, move closer to the subject, keep the background farther behind them, and use the lowest f-number your lens allows. With the 18–55mm kit lens, 50–55mm at f/5.6 is often more effective than shooting close at 18mm.',actions:[['Open aperture lesson','lesson:aperture',true],['Shoot a portrait','shoot:portrait',false]]},
    'dark':{title:'Why is the photo too dark?',body:'Exposure is a tradeoff. Open the aperture, slow the shutter only if the subject allows it, or raise ISO. If a person or handheld camera is involved, protect shutter speed first and let ISO rise.',actions:[['Exposure guide','lesson:aperture',true],['Practice ISO','lesson:iso',false]]},
    'noise':{title:'Why is my photo noisy?',body:'Noise usually appears because the scene is dark and ISO had to rise. More light, a wider aperture or a tripod can reduce the ISO you need. But a sharp ISO 1600 image is usually better than a blurry ISO 200 image.',actions:[['Open ISO lesson','lesson:iso',true],['Try simulator','#simulator',false]]},
    'portrait':{title:'What should I use for portraits?',body:'Start around 50–55mm, use the lowest available f-number, One-Shot AF and a single AF point on the nearest eye. Step back instead of shooting a face very close at 18mm.',actions:[['Portrait Guided Shoot','shoot:portrait',true],['Lens lesson','lesson:focal',false]]},
    'car':{title:'What settings should I use for a car?',body:'For a parked car, start around 35–55mm, ISO 100 outdoors, and roughly f/5.6–f/8. Watch reflections and bright highlights. For a moving car, switch priority to shutter speed—often 1/500 or faster.',actions:[['Car / product shoot','shoot:product',true],['Moving action shoot','shoot:action',false]]},
    'night':{title:'What should I do at night?',body:'Handheld at night, protect a usable shutter speed first. Start around 1/60 for still scenes, go faster for people, and raise ISO as required. Stabilization helps camera shake, but it cannot freeze a moving person.',actions:[['Night Guided Shoot','shoot:night',true],['ISO lesson','lesson:iso',false]]},
    'focus':{title:'Why is focus missing?',body:'Use one AF point when the subject matters. For a still subject, use One-Shot AF, place the point on the important detail, half-press to confirm focus, then shoot. For movement, use AI Servo and keep the point on the subject.',actions:[['Focus lesson','lesson:focus',true],['Find T7 AF controls','#camera',false]]},
    'sun':{title:'How do I shoot in harsh sunlight?',body:'Protect bright highlights first. Avoid exposing so far to the right that white areas lose detail. Change your angle, look for open shade, or use modest negative exposure compensation when the highlights matter.',actions:[['Check light conditions','#conditions',true],['Start Guided Shoot','shoot:portrait',false]]},
    'composition':{title:'How do I make photos look more professional?',body:'Before changing settings, simplify the frame. Move your feet, clean the background, check every edge, choose one clear subject and use lines or foreground deliberately. Strong composition often makes the biggest visible improvement.',actions:[['Composition lesson','lesson:composition',true],['Practice a frame','shoot:landscape',false]]}
  };

  function setLesson(key){try{localStorage.setItem('canonLearnActive',key)}catch{};location.hash='learn';setTimeout(()=>{const b=$(`#learnList button[data-lesson="${key}"]`);b?.click();b?.scrollIntoView({behavior:'smooth',block:'nearest'})},60)}
  function setShoot(subject){window.T7Store?.set?.('shootSubject',subject);window.T7Store?.set?.('shootScene',null);try{localStorage.setItem('canonT7LastShootSubject',subject);localStorage.removeItem('canonT7LastScene')}catch{}location.hash='shoot'}
  function navigate(action){if(!action)return;if(action.startsWith('lesson:'))return setLesson(action.split(':')[1]);if(action.startsWith('shoot:'))return setShoot(action.split(':')[1]);location.hash=action.replace(/^#/,'')}

  const hub=document.createElement('section');hub.className='photography-guide';hub.id='photographyGuide';
  hub.innerHTML=`<div class="pg-hero"><span class="pg-eyebrow">PHOTOGRAPHY GUIDE · REBEL T7</span><h1>Learn photography by making photographs.</h1><p>Use this as your field guide: understand the idea, see the T7 setting that controls it, try a shot, review what happened, then repeat.</p><div class="pg-search"><span id="pgSearchIcon"></span><input id="pgSearch" type="text" autocomplete="off" placeholder="Ask: blurry photo, portrait, night, car, background blur…" aria-label="Search photography guide"><button id="pgSearchGo">Guide me</button></div><div class="pg-quick" id="pgQuick"></div><div class="pg-result" id="pgResult"></div></div><section class="pg-section"><div class="pg-section-head"><div><small>FIELD GUIDE</small><h2>What do you want to learn?</h2></div><p>Start with the fundamentals, then learn the situations you actually photograph.</p></div><div class="pg-topic-grid" id="pgTopics"></div></section><section class="pg-section"><div class="pg-section-head"><div><small>QUICK FIXES</small><h2>When a photo goes wrong</h2></div><p>Diagnose the cause before randomly changing settings.</p></div><div class="pg-problems" id="pgProblems"></div></section><section class="pg-section"><div class="pg-section-head"><div><small>T7 CHEAT SHEET</small><h2>Which mode should I use?</h2></div><p>Use modes as tools. You do not need Manual mode for every photo.</p></div><div class="pg-cheats"><article class="pg-cheat"><div class="pg-cheat-top"><span class="pg-mode">Av</span><small>APERTURE PRIORITY</small></div><b>You control depth of field.</b><p>Best when the scene is mostly still and background blur or depth matters.</p><ul><li>Portraits and products</li><li>Landscapes when light is stable</li><li>Camera chooses shutter speed</li></ul></article><article class="pg-cheat"><div class="pg-cheat-top"><span class="pg-mode">Tv</span><small>SHUTTER PRIORITY</small></div><b>You control motion.</b><p>Best when freezing or showing movement matters more than depth of field.</p><ul><li>People walking</li><li>Cars and sports</li><li>Camera chooses aperture</li></ul></article><article class="pg-cheat"><div class="pg-cheat-top"><span class="pg-mode">M</span><small>MANUAL</small></div><b>You control both.</b><p>Best when the lighting is consistent or a screen/flash setup needs repeatability.</p><ul><li>TV / screen scenes</li><li>Controlled product work</li><li>Repeatable exposures</li></ul></article></div></section>`;
  const anchor=learn.querySelector('.learn-v2-head')||learn.firstElementChild;learn.insertBefore(hub,anchor);
  $('#pgSearchIcon').appendChild(icon('search'));

  const quick=[['all','All'],['start','Start here'],['creative','Creative'],['scenes','Real scenes'],['editing','Editing']];let active='all';
  function renderTopics(){const host=$('#pgTopics');host.innerHTML='';topics.filter(t=>active==='all'||t.group===active).forEach(t=>{const b=document.createElement('button');b.className='pg-topic';b.dataset.guide=t.id;b.style.setProperty('--pg-color',t.color);b.style.setProperty('--pg-glow',t.color+'22');b.innerHTML=`<span class="pg-topic-icon"></span><small>${esc(t.eyebrow)}</small><b>${esc(t.title)}</b><p>${esc(t.desc)}</p><span class="pg-topic-arrow">→</span>`;b.querySelector('.pg-topic-icon').appendChild(icon(t.icon));b.onclick=()=>{if(t.lesson)return setLesson(t.lesson);if(t.shoot)return setShoot(t.shoot);if(t.href)location.hash=t.href.replace(/^#/,'')};host.appendChild(b)})}
  function renderQuick(){const host=$('#pgQuick');host.innerHTML='';quick.forEach(([id,label])=>{const b=document.createElement('button');b.textContent=label;b.classList.toggle('active',id===active);b.onclick=()=>{active=id;renderQuick();renderTopics()};host.appendChild(b)})}

  const problemDefs=[['blurry','shutter','My photo is blurry'],['background','aperture','I want more background blur'],['focus','focus','The camera focused wrong'],['dark','exposure','My photo is too dark'],['noise','iso','My photo looks noisy'],['composition','guide','My photos look ordinary']];
  function renderProblems(){const host=$('#pgProblems');host.innerHTML='';problemDefs.forEach(([key,ic,label])=>{const a=document.createElement('button');a.className='pg-problem';a.innerHTML=`<span class="pg-problem-icon"></span><span><b>${esc(label)}</b><span>${esc(answers[key].body.split('. ')[0]+'.')}</span></span><em>›</em>`;a.querySelector('.pg-problem-icon').appendChild(icon(ic));a.onclick=()=>showAnswer(key);host.appendChild(a)})}
  function showAnswer(key){const a=answers[key];if(!a)return;const box=$('#pgResult');box.innerHTML=`<small>GUIDE ANSWER</small><h3>${esc(a.title)}</h3><p>${esc(a.body)}</p><div class="pg-result-actions"></div>`;const acts=box.querySelector('.pg-result-actions');a.actions.forEach(([label,action,primary])=>{const link=document.createElement('a');link.href=action.startsWith('#')?action:'#learn';link.textContent=label;if(primary)link.classList.add('primary');link.onclick=e=>{e.preventDefault();navigate(action)};acts.appendChild(link)});box.classList.add('show');box.scrollIntoView({behavior:'smooth',block:'nearest'})}
  function search(){const q=$('#pgSearch').value.trim().toLowerCase();if(!q)return;let key='';if(/blur|shak|motion/.test(q)&&!/background/.test(q))key='blurry';else if(/background|bokeh|depth/.test(q))key='background';else if(/focus|soft|sharp/.test(q))key='focus';else if(/dark|underexpos|brighten/.test(q))key='dark';else if(/noise|grain|iso/.test(q))key='noise';else if(/portrait|person|people/.test(q))key='portrait';else if(/car|vehicle|product/.test(q))key='car';else if(/night|low light|indoor/.test(q))key='night';else if(/sun|harsh|highlight/.test(q))key='sun';else if(/composition|professional|frame|ordinary/.test(q))key='composition';if(key)return showAnswer(key);const matches=topics.filter(t=>(t.title+' '+t.desc+' '+t.eyebrow).toLowerCase().includes(q));if(matches[0]){const t=matches[0];const box=$('#pgResult');box.innerHTML=`<small>GUIDE MATCH</small><h3>${esc(t.title)}</h3><p>${esc(t.desc)}</p><div class="pg-result-actions"><a class="primary" href="#">Open ${esc(t.title)}</a></div>`;box.querySelector('a').onclick=e=>{e.preventDefault();if(t.lesson)setLesson(t.lesson);else if(t.shoot)setShoot(t.shoot);else if(t.href)location.hash=t.href.replace(/^#/,'')};box.classList.add('show');return}const box=$('#pgResult');box.innerHTML='<small>GUIDE TIP</small><h3>Start with the cause.</h3><p>Try describing what is wrong with the photo: blurry, too dark, noisy, focus missed, background not blurry, harsh sunlight, portrait, car, or night.</p>';box.classList.add('show')}
  $('#pgSearchGo').onclick=search;$('#pgSearch').onkeydown=e=>{if(e.key==='Enter')search()};
  renderQuick();renderTopics();renderProblems();
  window.T7PhotographyGuide={showAnswer,setLesson,setShoot,version:'1.0.0'};
})();
