(()=>{
  if(window.T7Portfolio)return;
  const $=s=>document.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const KEY='canonT7PortfolioV1';
  let state=read(),history=[],compare=[],activeView='all',sheetRecord=null;

  function read(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return x&&typeof x==='object'?{favorites:Array.isArray(x.favorites)?x.favorites.map(String):[],collections:x.collections&&typeof x.collections==='object'?x.collections:{}}:{favorites:[],collections:{}}}catch{return{favorites:[],collections:{}}}}
  function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}window.dispatchEvent(new CustomEvent('t7-portfolio-updated',{detail:{state,compare:compare.slice(),activeView}}))}
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function idOf(r){return String(Number(r?.id||r?.time||0))}
  function finite(v){return Number.isFinite(Number(v))&&Number(v)>0}
  function cap(v){const s=String(v||'Photo');return s.charAt(0).toUpperCase()+s.slice(1)}
  function titleOf(r){return r?.sceneName||cap(r?.goal||'Photo')}
  function shutter(v){if(!finite(v))return'';v=Number(v);return v>=1?`${Math.round(v*10)/10}s`:`1/${Math.max(1,Math.round(1/v))}`}
  function settings(r){const e=r?.exif||{},p=[];if(finite(e.focal))p.push(`${Math.round(Number(e.focal))}mm`);if(finite(e.aperture))p.push(`f/${Math.round(Number(e.aperture)*10)/10}`);if(finite(e.exposure))p.push(shutter(e.exposure));if(finite(e.iso))p.push(`ISO ${Math.round(Number(e.iso))}`);return p.join(' · ')||r?.settings||'Settings unavailable'}
  function heart(){const s=document.createElementNS('http://www.w3.org/2000/svg','svg');s.classList.add('t7p-heart-svg');s.setAttribute('viewBox','0 0 24 24');s.setAttribute('aria-hidden','true');s.innerHTML='<path d="M20.8 4.6a5.4 5.4 0 0 0-7.6 0L12 5.8l-1.2-1.2a5.4 5.4 0 0 0-7.6 7.6L12 21l8.8-8.8a5.4 5.4 0 0 0 0-7.6Z"/>';return s}
  function icon(name){if(name==='heart')return heart();return window.T7Icons?.icon?.(name)||(()=>{const s=document.createElement('span');s.textContent='•';return s})()}
  function favorite(r){return state.favorites.includes(idOf(r))}
  function inCompare(r){const id=idOf(r);return compare.some(x=>idOf(x)===id)}
  function collectionList(){return Object.values(state.collections).sort((a,b)=>Number(a.created||0)-Number(b.created||0))}
  function photosInCollection(c){const ids=new Set((c?.photoIds||[]).map(String));return history.filter(x=>ids.has(idOf(x)))}
  function isInCollection(r,c){return (c?.photoIds||[]).map(String).includes(idOf(r))}

  function toggleFavorite(r){if(!r)return;const id=idOf(r),i=state.favorites.indexOf(id);if(i>=0)state.favorites.splice(i,1);else state.favorites.unshift(id);save();renderAll()}
  function toggleCompare(r){if(!r)return;const id=idOf(r),i=compare.findIndex(x=>idOf(x)===id);if(i>=0)compare.splice(i,1);else{if(compare.length>=2)compare.shift();compare.push(r)}renderAll();if(compare.length===2)setTimeout(openCompare,120)}
  function createCollection(name,r=null){name=String(name||'').trim().slice(0,42);if(!name)return null;const id='c'+Date.now().toString(36),c={id,name,created:Date.now(),photoIds:r?[idOf(r)]:[]};state.collections[id]=c;save();renderAll();return c}
  function toggleCollection(r,cid){const c=state.collections[cid];if(!r||!c)return;const id=idOf(r),ids=(c.photoIds||[]).map(String),i=ids.indexOf(id);if(i>=0)ids.splice(i,1);else ids.unshift(id);c.photoIds=ids;save();renderAll();renderSheet()}
  function deleteCollection(cid){const c=state.collections[cid];if(!c)return;if(!confirm(`Delete “${c.name}”? Photos stay in your Library.`))return;delete state.collections[cid];if(activeView===`collection:${cid}`)activeView='all';save();renderAll();renderSheet()}

  function ensureLibrary(){
    const lib=$('#library'),hero=lib?.querySelector('.library-hero');if(!lib||!hero)return;
    if(!$('#t7PortfolioBar')){
      const bar=document.createElement('section');bar.id='t7PortfolioBar';bar.className='t7-portfolio-bar';bar.innerHTML='<div class="t7p-bar-head"><div class="t7p-bar-title"><span id="t7pBarIcon"></span><div><small>PORTFOLIO</small><b>Favorites, collections & compare</b></div></div><button class="t7p-manage" id="t7pManage">Manage</button></div><div class="t7p-rail" id="t7pRail"></div><div class="t7p-compare-status" id="t7pCompareStatus"><span id="t7pCompareText"><b>0</b> of 2 selected</span><div class="t7p-compare-actions"><button id="t7pCompareClear">Clear</button><button class="primary" id="t7pCompareOpen">Compare</button></div></div>';
      hero.after(bar);$('#t7pBarIcon').appendChild(icon('library'));$('#t7pManage').prepend(icon('settings'));$('#t7pManage').onclick=()=>openSheet(null);$('#t7pCompareClear').onclick=()=>{compare=[];renderAll()};$('#t7pCompareOpen').onclick=openCompare;
      const view=document.createElement('section');view.id='t7PortfolioView';view.className='t7-portfolio-view';view.innerHTML='<div class="t7p-view-head"><div><small id="t7pViewKicker">PORTFOLIO VIEW</small><h2 id="t7pViewTitle">Favorites</h2></div><span id="t7pViewCount">0 photos</span></div><div class="t7p-grid" id="t7pGrid"></div>';bar.after(view);
    }
  }
  function chip(label,count,view,iconName){const b=document.createElement('button');b.className='t7p-chip'+(activeView===view?' active':'');b.appendChild(icon(iconName));const t=document.createElement('span');t.textContent=label;b.appendChild(t);if(count!=null){const e=document.createElement('em');e.textContent=String(count);b.appendChild(e)}b.onclick=()=>{activeView=view;renderAll()};return b}
  function renderToolbar(){ensureLibrary();const rail=$('#t7pRail');if(!rail)return;rail.innerHTML='';rail.appendChild(chip('All',history.length,'all','grid'));const favCount=history.filter(favorite).length;rail.appendChild(chip('Favorites',favCount,'favorites','heart'));collectionList().forEach(c=>rail.appendChild(chip(c.name,photosInCollection(c).length,`collection:${c.id}`,'folder')));const n=chip('New collection',null,'__new','plus');n.classList.add('new');n.onclick=()=>openSheet(null,true);rail.appendChild(n);const status=$('#t7pCompareStatus');status.classList.toggle('show',compare.length>0);$('#t7pCompareText').innerHTML=`<b>${compare.length}</b> of 2 selected`;$('#t7pCompareOpen').disabled=compare.length!==2}
  function nativeVisibility(filtered){const lib=$('#library'),keep=new Set([lib?.querySelector('.library-hero'),$('#t7PortfolioBar'),$('#t7PortfolioView')]);[...(lib?.children||[])].forEach(el=>{if(!keep.has(el))el.classList.toggle('t7p-native-hidden',filtered)})}
  function activeRecords(){if(activeView==='favorites')return history.filter(favorite);if(activeView.startsWith('collection:'))return photosInCollection(state.collections[activeView.split(':')[1]]);return history}
  function portfolioCard(r){
    const card=document.createElement('article');card.className='t7p-card';card.dataset.photoId=idOf(r);card.tabIndex=0;card.setAttribute('role','button');card.setAttribute('aria-label',`Open ${titleOf(r)} photo`);const src=r.preview||r.thumb||'';card.innerHTML=`<img src="${esc(src)}" alt="${esc(titleOf(r))} photo"><div class="t7p-card-copy"><small>${esc(new Date(r.time||Date.now()).toLocaleDateString([], {month:'short',day:'numeric'}).toUpperCase())}</small><b>${esc(titleOf(r))}</b><em>${esc(settings(r))}</em></div><div class="t7p-card-tools"></div>`;
    const tools=card.querySelector('.t7p-card-tools'),cmp=document.createElement('button'),fav=document.createElement('button');cmp.className='compare'+(inCompare(r)?' active':'');cmp.setAttribute('aria-label','Select photo for comparison');cmp.appendChild(icon('compare'));fav.className='favorite'+(favorite(r)?' active':'');fav.setAttribute('aria-label',favorite(r)?'Remove from favorites':'Add to favorites');fav.appendChild(icon('heart'));cmp.onclick=e=>{e.stopPropagation();toggleCompare(r)};fav.onclick=e=>{e.stopPropagation();toggleFavorite(r)};tools.append(cmp,fav);card.onclick=()=>window.T7PhotoViewer?.openRecord?.(r);card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();window.T7PhotoViewer?.openRecord?.(r)}};return card
  }
  function renderFiltered(){ensureLibrary();const view=$('#t7PortfolioView'),grid=$('#t7pGrid');if(!view||!grid)return;const filtered=activeView!=='all';nativeVisibility(filtered);view.classList.toggle('active',filtered);if(!filtered)return;const records=activeRecords(),isFav=activeView==='favorites',cid=activeView.startsWith('collection:')?activeView.split(':')[1]:null,c=cid?state.collections[cid]:null;$('#t7pViewKicker').textContent=isFav?'CURATED FRAMES':'COLLECTION';$('#t7pViewTitle').textContent=isFav?'Favorites':c?.name||'Collection';$('#t7pViewCount').textContent=`${records.length} photo${records.length===1?'':'s'}`;grid.innerHTML='';if(!records.length){grid.innerHTML=`<div class="t7p-empty" style="grid-column:1/-1"><div><b>${isFav?'No favorites yet':'This collection is empty'}</b><p>${isFav?'Tap the heart on a photo to start curating your strongest frames.':'Open a photo and use the collection button to add it here.'}</p></div></div>`;return}records.forEach(r=>grid.appendChild(portfolioCard(r)))}

  function decorateNative(){
    ensureLibrary();const gallery=history.filter(x=>x?.thumb).slice(0,5);$$('.library-gallery-shot').forEach((card,i)=>{const r=gallery[i];if(!r)return;card.dataset.photoId=idOf(r);let b=card.querySelector(':scope > .t7p-native-fav');if(!b){b=document.createElement('button');b.className='t7p-native-fav';b.setAttribute('aria-label','Favorite this photo');card.appendChild(b)}b.innerHTML='';b.appendChild(icon('heart'));b.classList.toggle('active',favorite(r));b.onclick=e=>{e.preventDefault();e.stopPropagation();toggleFavorite(r)}});
    const filter=$('#libFilter')?.value||'all',visible=(filter==='all'?history:history.filter(x=>x.goal===filter)).slice(0,24);$$('#libList .library-item').forEach((item,i)=>{const r=visible[i];if(!r)return;item.dataset.photoId=idOf(r);let b=item.querySelector(':scope > .t7p-native-fav');if(!b){b=document.createElement('button');b.className='t7p-native-fav';item.appendChild(b)}b.innerHTML='';b.appendChild(icon('heart'));b.setAttribute('aria-label',favorite(r)?'Remove from favorites':'Add to favorites');b.classList.toggle('active',favorite(r));b.onclick=e=>{e.preventDefault();e.stopPropagation();toggleFavorite(r)}})
  }

  const sheet=document.createElement('div');sheet.className='t7p-sheet-backdrop';sheet.id='t7pSheetBackdrop';sheet.innerHTML='<div class="t7p-sheet" role="dialog" aria-modal="true" aria-label="Collections"><div class="t7p-sheet-head"><div><small id="t7pSheetKicker">COLLECTIONS</small><h3 id="t7pSheetTitle">Manage collections</h3></div><button class="t7p-sheet-close" id="t7pSheetClose" aria-label="Close collections"></button></div><div class="t7p-collection-list" id="t7pCollectionList"></div><div class="t7p-new-collection"><input id="t7pNewCollectionName" maxlength="42" aria-label="New collection name" placeholder="New collection name"><button id="t7pCreateCollection" aria-label="Create collection">Create</button></div></div>';document.body.appendChild(sheet);$('#t7pSheetClose').appendChild(icon('close'));$('#t7pSheetClose').onclick=closeSheet;sheet.onclick=e=>{if(e.target===sheet)closeSheet()};$('#t7pCreateCollection').onclick=()=>{const input=$('#t7pNewCollectionName'),c=createCollection(input.value,sheetRecord);if(c){input.value='';renderSheet()}};$('#t7pNewCollectionName').onkeydown=e=>{if(e.key==='Enter')$('#t7pCreateCollection').click()};
  function openSheet(r=null,focusNew=false){sheetRecord=r;renderSheet();sheet.classList.add('open');document.body.classList.add('t7pv-lock');setTimeout(()=>focusNew?$('#t7pNewCollectionName').focus():$('#t7pSheetClose').focus(),30)}
  function closeSheet(){sheet.classList.remove('open');sheetRecord=null;if(!window.T7PhotoViewer?.isOpen?.())document.body.classList.remove('t7pv-lock')}
  function renderSheet(){const host=$('#t7pCollectionList');if(!host)return;$('#t7pSheetKicker').textContent=sheetRecord?'ADD PHOTO':'COLLECTIONS';$('#t7pSheetTitle').textContent=sheetRecord?'Add to collection':'Manage collections';host.innerHTML='';const list=collectionList();if(!list.length){host.innerHTML='<div class="t7p-empty" style="min-height:110px"><div><b>No collections yet</b><p>Create one below. Your photos remain in the main Library too.</p></div></div>';return}list.forEach(c=>{const row=document.createElement('div');row.className='t7p-collection-row';const count=photosInCollection(c).length;row.innerHTML=`<span class="t7p-collection-row-icon"></span><div><b>${esc(c.name)}</b><small>${count} photo${count===1?'':'s'}</small></div>`;row.querySelector('.t7p-collection-row-icon').appendChild(icon('folder'));const b=document.createElement('button');if(sheetRecord){const yes=isInCollection(sheetRecord,c);b.className='t7p-collection-toggle'+(yes?' active':'');b.textContent=yes?'Added':'Add';b.onclick=()=>toggleCollection(sheetRecord,c.id)}else{b.className='t7p-collection-delete';b.setAttribute('aria-label',`Delete ${c.name}`);b.appendChild(icon('trash'));b.onclick=()=>deleteCollection(c.id)}row.appendChild(b);host.appendChild(row)})}

  const cmpOverlay=document.createElement('div');cmpOverlay.className='t7p-compare-overlay';cmpOverlay.id='t7pCompareOverlay';cmpOverlay.innerHTML='<div class="t7pc-top"><div class="t7pc-title"><small>FRAME COMPARISON</small><b>Two photos · one decision</b></div><button class="t7pc-close" id="t7pcClose" aria-label="Close comparison"></button></div><div class="t7pc-stage" id="t7pcStage"></div><div class="t7pc-bottom"><div class="t7pc-insight"><small>WHAT CHANGED</small><b id="t7pcInsight">Compare the technical signals and the frame itself.</b></div><button id="t7pcClear" aria-label="Clear comparison">Clear comparison</button></div>';document.body.appendChild(cmpOverlay);$('#t7pcClose').appendChild(icon('close'));$('#t7pcClose').onclick=closeCompare;$('#t7pcClear').onclick=()=>{compare=[];closeCompare();renderAll()};
  function compareFrame(r,label){const e=settings(r),src=r.preview||r.thumb||'';return`<section class="t7pc-frame"><span class="t7pc-label">${label}</span><div class="t7pc-image"><img src="${esc(src)}" alt="${esc(titleOf(r))} ${label}"></div><div class="t7pc-info"><h3>${esc(titleOf(r))}</h3><div class="t7pc-exif">${esc(e)}</div><div class="t7pc-scores"><span>FOCUS<b>${Math.round(Number(r.detail||0))||'—'}</b></span><span>EXPOSURE<b>${Math.round(Number(r.exposure||0))||'—'}</b></span><span>TONE<b>${Math.round(Number(r.clipping||0))||'—'}</b></span><span>CONTRAST<b>${Math.round(Number(r.contrast||0))||'—'}</b></span></div></div></section>`}
  function comparisonInsight(a,b){const out=[],dd=Math.round(Number(b.detail||0)-Number(a.detail||0)),de=Math.round(Number(b.exposure||0)-Number(a.exposure||0));if(dd)out.push(`Focus ${dd>0?'+':''}${dd}`);if(de)out.push(`Exposure ${de>0?'+':''}${de}`);const ae=a.exif||{},be=b.exif||{};if(finite(ae.exposure)&&finite(be.exposure)&&Number(ae.exposure)!==Number(be.exposure))out.push(`${shutter(ae.exposure)} → ${shutter(be.exposure)}`);if(finite(ae.iso)&&finite(be.iso)&&Number(ae.iso)!==Number(be.iso))out.push(`ISO ${Math.round(ae.iso)} → ${Math.round(be.iso)}`);if(!out.length)return'The technical signals are very close. Judge expression, timing, light and composition.';return out.join(' · ')}
  function openCompare(){if(compare.length!==2)return;const [a,b]=compare;$('#t7pcStage').innerHTML=compareFrame(a,'A')+compareFrame(b,'B');$('#t7pcInsight').textContent=comparisonInsight(a,b);cmpOverlay.classList.add('open');document.body.classList.add('t7pv-lock')}
  function closeCompare(){cmpOverlay.classList.remove('open');if(!window.T7PhotoViewer?.isOpen?.()&&!sheet.classList.contains('open'))document.body.classList.remove('t7pv-lock')}

  function ensureViewerControls(){const host=$('#t7pvTopActions'),count=$('#t7pvCount');if(!host||$('#t7pViewerFavorite'))return;const defs=[['t7pViewerFavorite','heart','Favorite photo'],['t7pViewerCollection','folder','Add photo to collection'],['t7pViewerCompare','compare','Compare photo']];defs.forEach(([id,n,label])=>{const b=document.createElement('button');b.id=id;b.className='t7p-viewer-btn';b.setAttribute('aria-label',label);b.appendChild(icon(n));host.insertBefore(b,count)});$('#t7pViewerFavorite').onclick=()=>{const r=window.T7PhotoViewer?.getCurrent?.();toggleFavorite(r)};$('#t7pViewerCollection').onclick=()=>openSheet(window.T7PhotoViewer?.getCurrent?.()||null);$('#t7pViewerCompare').onclick=()=>toggleCompare(window.T7PhotoViewer?.getCurrent?.());updateViewer()}
  function updateViewer(){ensureViewerControls();const r=window.T7PhotoViewer?.getCurrent?.();if(!r)return;const fav=$('#t7pViewerFavorite'),cmp=$('#t7pViewerCompare'),col=$('#t7pViewerCollection');fav?.classList.toggle('active',favorite(r));fav?.classList.add('favorite');cmp?.classList.toggle('active',inCompare(r));cmp?.classList.add('compare');const any=collectionList().some(c=>isInCollection(r,c));col?.classList.toggle('active',any);fav?.setAttribute('aria-label',favorite(r)?'Remove from favorites':'Add to favorites');cmp?.setAttribute('aria-label',inCompare(r)?'Remove from comparison':'Add to comparison')}

  async function refreshHistory(items=null){try{history=items||await window.T7History?.all?.()||[]}catch{history=[]}renderAll()}
  function renderAll(){ensureLibrary();renderToolbar();renderFiltered();decorateNative();updateViewer();if(sheet.classList.contains('open'))renderSheet()}

  window.addEventListener('t7-photo-viewer-changed',()=>setTimeout(updateViewer,0));
  window.addEventListener('t7-history-updated',e=>refreshHistory(e.detail?.items||null));
  window.addEventListener('t7-route-changed',e=>{if(e.detail?.route==='library')setTimeout(()=>refreshHistory(),80)});
  $('#libFilter')?.addEventListener('change',()=>setTimeout(decorateNative,80));
  window.addEventListener('keydown',e=>{if(e.key==='Escape'&&cmpOverlay.classList.contains('open'))closeCompare();else if(e.key==='Escape'&&sheet.classList.contains('open'))closeSheet()});
  setTimeout(()=>refreshHistory(),360);

  window.T7Portfolio={toggleFavorite,toggleCompare,openCompare,openCollections:openSheet,getState:()=>JSON.parse(JSON.stringify(state)),getCompare:()=>compare.slice(),setView:v=>{activeView=v;renderAll()},version:'1.0.0'};
})();