(()=>{
  const $=s=>document.querySelector(s),learn=$('#learn');if(!learn||window.T7PracticeCoach)return;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const drills={
    indoorSlowShutter:{title:'Build a safer indoor shutter habit',skill:'Shutter speed',why:'Your Library noticed repeated indoor shots using a shutter speed that is risky for handheld sharpness.',setup:'Tv · 35mm · One-Shot AF · Auto ISO',shots:[['1/60','Take the baseline shot. Notice whether hand movement or the subject makes detail soft.'],['1/125','Take the same frame again. Keep your position and focus point the same.'],['1/250','Take a third frame. Let Auto ISO rise if necessary so shutter speed is the only deliberate change.']],look:'Compare fine text, eyes, logos or edges. Pick the slowest shutter that is consistently sharp enough for the subject.',href:'#shoot',cta:'Open Guided Shoot',subject:'indoor'},
    portraitWide:{title:'See what 18mm vs 55mm does to a portrait',skill:'Focal length',why:'Your Library noticed that recent portraits are often being shot on the wide end of the kit lens.',setup:'Av · f/5.6 · ISO Auto · One-Shot AF',shots:[['18mm','Photograph the same person or object without moving the camera.'],['35mm','Zoom to 35mm and take the same composition from the same position.'],['55mm','Zoom to 55mm. Then step back only if needed to match the subject size.']],look:'Compare face/object shape, background size and separation. The point is to feel why 50–55mm often works better for portraits.',href:'#shoot',cta:'Start a portrait shoot',subject:'portrait'},
    actionSlow:{title:'Learn what actually freezes movement',skill:'Shutter speed',why:'Your Library noticed action shots using shutter speeds below the safer freezing range.',setup:'Tv · AI Servo AF · Continuous drive · Auto ISO',shots:[['1/250','Track a walking person, moving car at a safe distance, or another moving subject.'],['1/500','Repeat the same movement and framing.'],['1/1000','Repeat again while tracking before pressing fully.']],look:'Compare moving edges, hands, wheels or hair. See when subject motion stops smearing—not just when the whole image looks brighter or darker.',href:'#shoot',cta:'Start an action shoot',subject:'action'},
    highIsoSlow:{title:'Make higher ISO buy you shutter speed',skill:'ISO + shutter',why:'Your Library noticed high ISO appearing while shutter speed was still relatively slow.',setup:'M · widest useful aperture · One-Shot AF',shots:[['ISO 800 · 1/60','Take a low-light baseline.'],['ISO 1600 · 1/125','Double ISO and double shutter speed. Keep aperture and framing the same.'],['ISO 3200 · 1/250','Repeat the trade once more if the scene is dark enough.']],look:'Compare noise against sharpness. The goal is to learn when a noisier but sharper frame is the better file.',href:'#simulator',cta:'Open exposure simulator'},
    highlights:{title:'Practice protecting bright detail',skill:'Exposure',why:'Your Library noticed repeated weak highlight protection.',setup:'Av · ISO 100–400 · same framing',shots:[['0 EV','Take the camera-metered baseline.'],['−1/3 EV','Reduce exposure compensation slightly and shoot again.'],['−2/3 EV','Reduce it one more step and compare bright detail.']],look:'Look at white clouds, reflections, screens or bright objects. Pick the brightest exposure that still preserves important texture.',href:'#camera',cta:'Find the Av ± control'},
    soft:{title:'Run a controlled focus test',skill:'Focus',why:'Your Library found repeated weak focus/detail signals with enough confidence to justify a controlled test.',setup:'Av · 55mm · f/5.6 · ISO Auto · 1/250+ target',shots:[['Shot 1','Choose one AF point and place it on clear lettering or a high-contrast edge. Half-press, confirm focus, then shoot.'],['Shot 2','Repeat without changing distance or framing.'],['Shot 3','Repeat once more, concentrating on a smooth shutter press.']],look:'If all three are sharp, your camera/lens can focus fine and the issue is likely technique or shutter speed in real scenes. If all three miss similarly, investigate focus setup further.',href:'#camera',cta:'Open AF controls'},
    landscapeIso:{title:'Build a low-ISO landscape habit',skill:'ISO',why:'Your Library noticed landscapes using unusually high ISO.',setup:'Av · 18–24mm · f/8 · stable support',shots:[['ISO 100','Stabilize the camera and take the first frame.'],['ISO 400','Keep aperture and framing the same and take another.'],['Handheld check','If you remove the support, raise ISO only enough to keep the shutter safe.']],look:'Zoom into fine texture. Learn when the lower ISO is worth a slower shutter because the subject is static and the camera is supported.',href:'#shoot',cta:'Start a landscape shoot',subject:'landscape'},
    landscapeAperture:{title:'See depth of field change in a landscape',skill:'Aperture',why:'Your Library noticed landscapes repeatedly using a very wide aperture.',setup:'Av · 18–24mm · ISO 100 · stable support',shots:[['f/4–f/5.6','Focus on a mid-distance detail and take the wide-aperture baseline.'],['f/8','Keep the focus point and framing the same.'],['f/11','Take one more frame if light/support allows it.']],look:'Compare foreground and background detail, not just brightness. f/8 is often the useful middle ground.',href:'#shoot',cta:'Start a landscape shoot',subject:'landscape'}
  };

  const card=document.createElement('section');card.className='practice-coach-card';card.hidden=true;
  const head=learn.querySelector('.learn-v2-head')||learn.firstElementChild;head?.insertAdjacentElement('afterend',card);

  function history(){return window.T7Store?.get('practiceHistory',[])||[]}
  function saveDone(insight){const h=history(),entry={id:insight.id,title:insight.title,skill:insight.skill,time:Date.now()};window.T7Store?.set('practiceHistory',[entry,...h].slice(0,20));window.T7Store?.remove('practiceInsight');render()}
  function render(){
    const insight=window.T7Store?.get('practiceInsight',null),d=insight&&drills[insight.id];
    if(!d){card.hidden=true;card.innerHTML='';return}
    card.hidden=false;card.innerHTML=`<div class="practice-coach-head"><div><small>PERSONAL PRACTICE</small><h2>${esc(d.title)}</h2><p>${esc(d.why)}</p></div><button type="button" id="practiceDismiss" aria-label="Dismiss practice drill">×</button></div><div class="practice-coach-setup"><small>STARTING SETUP</small><b>${esc(d.setup)}</b></div><div class="practice-coach-shots">${d.shots.map((s,i)=>`<div><i>${i+1}</i><span><b>${esc(s[0])}</b><small>${esc(s[1])}</small></span></div>`).join('')}</div><div class="practice-coach-look"><small>WHAT TO LOOK FOR</small><p>${esc(d.look)}</p></div><div class="practice-coach-actions"><a href="${d.href}" id="practiceStart">${esc(d.cta)}</a><button type="button" id="practiceDone">Mark drill complete</button></div>`;
    $('#practiceDismiss').onclick=()=>{window.T7Store?.remove('practiceInsight');render()};
    $('#practiceDone').onclick=()=>saveDone(insight);
    $('#practiceStart').onclick=()=>{if(d.subject){window.T7Store?.set('shootSubject',d.subject);window.T7Store?.set('shootScene',null)}};
  }
  window.addEventListener('t7-store-change',e=>{if(e.detail?.name==='practiceInsight')render()});window.addEventListener('t7-route-changed',e=>{if(e.detail?.route==='learn')render()});
  window.T7PracticeCoach={drills,render,version:'1.0.0'};setTimeout(render,120);
})();